### ISSUE TITLE
Fix item-submission.xml DTD

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2786]
Currently the DTD is not valid for the new item-submission.xml format. https://jira.lyrasis.org/browse/DS-4264

**Comment by Raf-atmire** [comment]
@tdonohue I've had a look at this issue and it seems to me that we're running into a conceptual problem here. There are currently two different "step" tags present within this item-submission.xml:
- https://github.com/DSpace/DSpace/blob/main/dspace/config/item-submission.xml#L49
- https://github.com/DSpace/DSpace/blob/main/dspace/config/item-submission.xml#L195

One of these step tags contains a heading, processing-class and type element. The other step is without any of these elements  (and shouldn't ever contain any of these elements). This means that, conceptually, we're dealing with two different "step" xml tags whilst a .dtd is only able to properly identify and describe a single xml tag with a given name.

This leaves us with two options:
- We alter the <a href="https://github.com/DSpace/DSpace/blob/main/dspace/config/item-submission.dtd#L21">dtd</a> at this location to make every element optional for the "step" xml tag
- We change the name of one of the "step" xml tags so that we're able to properly define both

I heavily prefer the second option. If we were to simply make everything with regards to "step" optional in the dtd, then it would basically mean that we don't have a dtd because nothing is enforced and we could easily allow mistakes to happen in these xml files because we have no system of checking.
The second option would allow us to keep the enforcing rules on both elements, making the entire setup more stable.

The second option has the drawback of taking a lot more time to implement. We'll have to change the xml file and the dtd file, but we'll also likely have to alter the parsing of these files.

**Comment by mwoodiupui** [comment]
I heartily agree with the objection concerning validation, but I note that at the moment we are using a non-validating parser so none of our definitions are enforced during syntactic analysis anyway.  SubmissionConfigReader is peppered with tests to ensure that required elements are present.

A third option:  translate the DTD to XML Schema, renaming one of the two "step" elements.  Scrap all of our hand-built tree-parsing code and generate it automatically from the schema using jaxb2-maven-plugin.  This approach is probably the most disruptive of surrounding code, but it hands us the data structures that we need, ready to drive the submission-wizard engine.

**Comment by tdonohue** [comment]
@Raf-atmire :  Good point.  I agree with your analysis. Could you provide a rough estimate of how much more time it would take to implement the second option (rename one step tag)?  Are we talking a few extra hours?

Looking more closely here, I suspect the `<step>` under `<step-definitions>` could be **renamed** to be either `<step-definition>` or `<step-def>`.  It's role is to define the step.

That would mean the `<step>` under `<submission-process>` could keep the same name.  We may want to change it's `id` attribute though, as that references back to the `step-definition`.  Maybe that should be renamed to `definition-id` (or similar).

So we'd end up with something like this...
```
<step-definitions>
    <step-definition id="sample">
         <heading>Sample Step</heading>
         <processing-class>...</processing-class>
         <type>sample</type>
    </step-definition>
    ...
</step-definitions>
<submission-definitions>
    <submission-process name="traditional">
        <step definition-id="sample"/>
          ....
    </submission-process>
</submission-definitions>
```

@mwoodiupui : While I definitely understand the desire to scrap DTDs in favor of XML Schema + automatic code generator (like jaxb), that's unfortunately out-of-scope for the current DSpace 7.0 development effort / budget.  I do agree with you though that we may want to consider this for the long term (for all XML-based configs), as it'd be less code for us to write/maintain manually.  (Though, at the same time, we might also want to question honestly whether XML-based configs should be replaced with something easier to manage...that's another topic altogether we should consider here.)

**Comment by mwoodiupui** [comment]
If we enable validation, then I think that `submission-definitions` | `submission-process` | `step` | `@id` *must* be renamed, else it is required to be unique within the document, and I don't think we mean that.  The point of separating out `step-definitions` is that a `step-definition` should be reusable in multiple `submission-definition`s, no?

However `step-definition`s *should* have unique names, and `@id` fills that bill perfectly.

**Comment by Raf-atmire** [comment]
@tdonohue I estimate the rewriting of the step tag under the `step-definitions` like you've mentioned to be about 4 hours of implementation work and testing work combined.

**Comment by tdonohue** [comment]
@Raf-atmire : Sounds fine. I've updated the estimate on this ticket to be **6 hrs** (originally 2 hours + your 4 hour estimate)
