### ISSUE TITLE
DS-4503: [Google Scholar] In REST API v7, citation_pdf_url must be based on the Angular UI hostname

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2809]
This is a duplicate of [DS-4503](https://jira.lyrasis.org/browse/DS-4503)

Estimate from release plan: TBD
Expressing interest: none

Reported by Google Scholar after reviewing indexing on https://dspace7-demo.atmire.com/

Currently, the "citation_pdf_url" returns the REST API URL where the PDF can be downloaded, for example:

<meta property="citation_pdf_url" content="https://dspace7.4science.cloud/server/api/core/bitstreams/6260ead5-90d6-405c-a524-f4a254c0bf10/content">

This will cause SEO issues if the REST API and Angular UI have different hostnames (which is what exists on our demo site). In order to avoid this, we will need to provide a Angular UI URL that is essentially a "pass through" to the backend to download the PDF. So, it could be something like "https://dspace7-demo.atmire.com/bitstreams/6260ead5-90d6-405c-a524-f4a254c0bf10/content"

**Comment by tdonohue** [comment]
I've removed the `Estimate TBD` as we believe (at this time) that no work will be needed on the REST API backend to support https://github.com/DSpace/dspace-angular/issues/737.  The reason is that all `citation_*` tags are now being built on the frontend, as described in [this comment on 737](https://github.com/DSpace/dspace-angular/issues/737#issuecomment-685802966)

I've assigned @artlowel to this ticket as he'll report back (once 737 work has begun) on whether backend work is necessary. If so, we can obtain an updated estimate at that time.

**Comment by tdonohue** [comment]
It was determined no changes were needed on the REST API.  Instead, this is able to be fixed entirely in the UI layer by https://github.com/DSpace/dspace-angular/pull/868  

Therefore, I'm closing this ticket as there's no REST API work to be done.
