### ISSUE TITLE
Sherpa-Romeo Integration

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2840]
From release plan spreadsheet

Estimate from release plan: 56 hours
Expressing interest: none

Should use new "externalsources" endpoint, similar to ORCID.

This ticket is specific to REST API changes.  Related UI ticket at: DSpace/dspace-angular#769

**Comment by tdonohue** [comment]
Basic SHERPA/RoMEO integration already exists in 7.0.  Needs discussion as to what additional features are needed. May be overestimated.

**Comment by abollini** [comment]
@tdonohue this task was about the integration of sherpa rome in the submission to support the upload of suitable open access version of the fulltext according to the publishing agreement.
In the previous version, at least for JSPUI not sure for XMLUI the RoMEO information was show in a side column in the upload step. I suggest to implement it as a separate panel in the new DSpace 7 submission.
To respect the submission architecture that expect to have all the information as part of the work*item serialization a local cache of the romeo data is required otherwise we will need to call the service each time that the work*item is retrieved.
IMHO the REST estimation is probably a bit optimistic and should be raised up to 80 hours.

**Comment by tdonohue** [comment]
Thanks @abollini for helping clarify this ticket & adding an updated estimation. I've updated this ticket and the Angular ticket https://github.com/DSpace/dspace-angular/issues/769#issuecomment-974848427 with your new estimates.

**Comment by abollini** [comment]
@tdonohue we are interested on that, I guess that the "needs discussion" label was left accidentally

**Comment by davidatmire** [comment]
Just a note that different institutions are showing interest for this feature, especially when they are upgrading from pre-DSpace 7 versions which already had the integration before (both in JSPUI and XMLUI)

**Comment by tdonohue** [comment]
@davidatmire : This ticket is on our 7.3 board already & assigned to @abollini 's team. It will very likely be completed for the 7.3 release.
