### ISSUE TITLE
Support for controlled-vocabulary - Hierarchical facets

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2870]
From the release spreadsheet
Estimate from release plan: TBD
Expressing interest: none

No details added; note that a volunteer is needed.

Frontend ticket: https://github.com/DSpace/dspace-angular/issues/815

**Comment by abollini** [comment]
just a note for 7.5, our estimation for this task on the backend is 48 hours

**Comment by tdonohue** [comment]
See [comment on frontend ticket](https://github.com/DSpace/dspace-angular/issues/815#issuecomment-1293769514).  Per discussion in today's meeting this has been reassigned to Atmire (@artlowel ).  The estimate here is zeroed out because it's included in the estimate for [#815](https://github.com/DSpace/dspace-angular/issues/815)

@artlowel : Please feel free though to verify estimate is correct and let me know if any updates are needed.

**Comment by tdonohue** [comment]
Closing, fixed by #8600 and https://github.com/DSpace/dspace-angular/pull/1988
