### ISSUE TITLE
Configure whether personal data stored in Provenance

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2889]
From release plan spreadsheet
Estimate from release plan: TBD
Expressing interest: none

DSpace should include a configuration that disables storing personal information (email, netid, name) in the dc.description.provenance field.  Currently, this info is automatically stored when items are submitted or reviewed.

**Comment by damian-joz** [comment]
@tdonohue 
As PCG Academia we would like to contribute to this task. @AndrewAlesik can start an implementation right away.

**Comment by tdonohue** [comment]
@damian-joz : Thanks! Please be aware that this may be unlikely to make it into 8.0 at this point, since we are only accepting bug fixes / small improvements.  Nonetheless, you are welcome to begin working on this, and when it is ready submit a PR (which likely would be scheduled for 9.0).

Assigning you to this ticket, but delegate the actual work to whomever you want.

**Comment by damian-joz** [comment]
Thanks @tdonohue . I can't reassign to anyone else so please assign @AndrewAlesik to the issue.

**Comment by tdonohue** [comment]
@damian-joz : To be clear, the person who develops on this task does *not* need to be assigned to the ticket.  The ticket just needs to be assigned to someone on your team so that I know who to contact if there are questions.

I cannot assign @AndrewAlesik either as GitHub is blocking my ability to assign him until he either adds a comment to this ticket or is added as a full developer to the DSpace project in GitHub. 

With other service providers, I just make sure that someone at the service provider is assigned.  It doesn't matter who actually does the work or creates the PR.  Just make sure the PR links back to this ticket.

**Comment by damian-joz** [comment]
Hi @tdonohue 

We've prepared the PR: https://github.com/DSpace/DSpace/pull/9442
I think it could still be a part of DSpace 8.0 if we could find a reviewer quickly as it is a small PR.
