### ISSUE TITLE
CSV import error with virtual metadata

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#2900]
**Describe the bug**
When testing https://github.com/DSpace/dspace-angular/pull/798, I noticed that the import feature doesn't know yet how to deal with virtual metadata.

**To Reproduce**
1. When using the Import Metadata feature
2. If you data contains `::virtual::` metadata
Like:
```
id,collection,dc.contributor.author,dc.date.accessioned,dc.date.available,dc.date.issued,dc.description.abstract[por],dc.description.provenance[en],dc.identifier,dc.identifier.citation[por],dc.identifier.issn,dc.identifier.other,dc.identifier.uri,dc.language.iso[por],dc.publisher[por],dc.rights[por],dc.title,dc.title[por],dc.type[por],relation.isAuthorOfPublication,relationship.type
"d6c11171-4e9e-4f20-8e57-cba279a77755","123456789/2","Deleted4, John::virtual::4::600||Delete2, John||Delete, John||Delete, John||Kolmakov, Nikolai N.","2020-01-24T14:25:48Z","2020-01-24T14:25:48Z","2008-09-20","Not To delete - The goldfish","Made available in DSpace on 2020-01-24T14:25:48Z (GMT). No. of bitstreams: 0
  Previous issue date: 2008-09-20","http://dx.doi.org/10.1186/1471-2164-9-429","BMC Genomics, 9, 1, 429-429, 2008.","1471-2164","AUT: ACA00258","https://dev5.rcaap.pt/handle/123456789/9","eng","BioMed Central","openAccess",,"To delete","article","61f90aa1-5522-4fcb-93fa-444434079230::virtual::4::600||665f40e2-242a-4c24-814c-bfc96737741f","Publication"
"ca380107-5bd9-4310-9b61-9e56d2bbee27","123456789/2","Graça, Paulo","2020-04-30T18:08:49Z","2020-04-30T18:08:49Z","2020",,"Made available in DSpace on 2020-04-30T18:08:49Z (GMT). No. of bitstreams: 1
2018-01-25 13_59_18-Windows Update.pdf: 420702 bytes, checksum: c114348192905236347d0c2e3ee12d31 (MD5)
  Previous issue date: 2020",,,,,"http://localhost:3000/handle/123456789/13",,,,"Title",,,,
```
3. You will get a failure process status
4. And an Error
Like:
```
2020-07-23 11:35:03,219 ERROR org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler @ Process id: 6, script name: metadata-import, message: org.dspace.app.bulkedit.MetadataImportException: Error in CSV row 1:
Bad metadata field in reference: '61f90aa1-5522-4fcb-93fa-444434079230::virtual::4::600' (expected syntax is schema.element[.qualifier])
        at org.dspace.app.bulkedit.MetadataImport.resolveEntityRef(MetadataImport.java:1536)
        at org.dspace.app.bulkedit.MetadataImport.resolveEntityRefs(MetadataImport.java:1408)
        at org.dspace.app.bulkedit.MetadataImport.runImport(MetadataImport.java:368)
        at org.dspace.app.bulkedit.MetadataImport.internalRun(MetadataImport.java:230)
        at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
The expected result is to be able to import content that has virtual metadata and those fields to be ignored in the item's metadata in the database but if required, update the relationship attributes between related items.

**Related work**
https://github.com/DSpace/dspace-angular/pull/798

**Additional Notes:**
Probably there are also some other issues, related with CSV metadata import/export that are needed to be also addressed, like:

- https://jira.lyrasis.org/browse/DS-4361
- https://jira.lyrasis.org/browse/DS-4402

**Comment by tdonohue** [comment]
@paulo-graca : This does sound like a bug.  That said, I'm not yet certain whether it's a bug in the *import* CSV process (as you noted above), or perhaps a bug in the *export* CSV process (in that we should never export an entry that says `::virtual::`).

Looking back at related past work, this bug seems somewhat related to #2471, which is where @cwilper and @benbosman added a feature to create/modify relationships in the import CSV process. So, I'd like their feedback here on how to fix this `::virtual::` problem, as it seems to be similar in that it is a question of how we manage/show relationships between items in an CSV file.  (For additional reference, it looks like this previous feature has ITs in [CSVMetadataImportReferenceIT](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/csv/CSVMetadataImportReferenceIT.java))

In any case, I think this definitely needs resolution.  I'm not yet certain whether to add this into `beta4` or `beta5`, but it should be fixed prior to 7.0 final. 

@cwilper or @benbosman: any thoughts on this bug?

**Comment by tdonohue** [comment]
@benbosman or @cwilper  :  I'd appreciate feedback on this bug report, if you have a chance.  I think it sounds like a backend issue, which I'm tentatively adding to beta5 (as it sounds related to Entities).  But, if you have other feedback on where to schedul this ticket, let me know.

**Comment by benbosman** [comment]
This can be a very simple fix, supporting e.g. `61f90aa1-5522-4fcb-93fa-444434079230::virtual::4::600` identical to `61f90aa1-5522-4fcb-93fa-444434079230` to identify the related item. Supporting this, combined with a test, should be realistic with 3 hours of work.
An alternative solution would be to parse the relationship id `600` and avoid replacing it with a new relationship. Since I don't expect that to be necessary, I'll assume relationships can be replaced if they are present in the CSV

**Comment by tdonohue** [comment]
That seems fine, along with the estimate of 3 hours.  Thanks @benbosman

**Comment by benbosman** [comment]
@tdonohue we've implemented quite a few bug fixes for the CSV import. I don't think any of them fixes this problem, but we would be interested in implementing this as well
