### ISSUE TITLE
Change the date format in Dspace

### ISSUE THREAD

**Issue by yasiriqbal1** [DSpace/DSpace#2941]
Dear All,
I hope you are doing well, we have recently deployed the dpsace. Dspace showed the document issue date in YY-MM-DD format by default but we want the format DD-MM-YY. Could it be possible in dspace.

**Comment by tdonohue** [comment]
Closing as this is a question rather than a bug report.  We recommend questions be asked using one of our support options: https://wiki.lyrasis.org/display/DSPACE/Support

As a sidenote, I'm not sure how easily this change could be made.  DSpace tends to store all dates are [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601).  It might be easiest to leave the dates as-is in DSpace's storage, but just customize the *User Interface* display to show the date in that format.  In any case, you may have more luck asking on the tech support lists to see if anyone else has made this sort of change before.
