### ISSUE TITLE
Refactor/remove custom MultipartFileSender to use Spring Boot Range requests

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2983]
**Describe the bug**
Discovered in analysis of #2962.  Solving this ticket would also fix #2962 

As noted [in this comment](https://github.com/DSpace/DSpace/issues/2962#issuecomment-690751137), our custom [MultipartFileSender](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/MultipartFileSender.java) is completely bypassing Spring Security & Spring automated tools. This means that is does NOT return CORS headers (and also would not receive CSRF protection) which are automatically returned by our Spring Security configuration in [WebSecurityConfiguration](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java).

We must refactor (or completely remove) the `MultipartFileSender` and use out of the box Spring Boot support for Range requests.  Some early ideas of how this might be done are included in these StackOverflow answers:
* https://stackoverflow.com/a/63393094 - describes how to support range headers this in Spring Boot v2 (which we use)
* https://stackoverflow.com/a/54615714 - links back to the code in Spring which seems to enable this to work. (This might just be something to reference if you hit issues in enabling this in Spring Boot)

_NOTE:_ At this time, it's unclear if Spring Boot supports ETags (which `MultipartFileSender` also supports).  However, in our meeting on Sept 24, the team decided that we can **drop ETag support** from this endpoint, as ETags are currently not supported by our REST API (and not scheduled for support in 7.0). 

**To Reproduce**
See ticket #2962, where this bug was initially reported

**Comment by jonas-atmire** [comment]
@tdonohue
We have estimated this as around 16 hours of implementation time, considering some additional pitfalls that we might not have thought of that could come up during the implementation.

As you mentioned 
> 'We must refactor (or completely remove) the MultipartFileSender... '

* Part of this update will be to change this 'MultipartFileSender' class to now only initialise the HTTPHeaders (So that we can rely on the spring framework to handle the MultiPart file sending)
	* The HTTPHeaders will be used in the ResponseEntity given by any methods that need to reply with a downloaded file. 
	* The class will also be renamed to better fit its functionality. 
	* The entire 'Range' logic can be removed from the previously name 'MultiPartFileSender' since spring should handle this for us.
* The SitemapRestController will be altered to adhere to the guidelines of returning a ResponseEntity as well 
* To properly handle the multipart file sending, the BitstreamRestController will then return a new ResponseEntity for the bitstream resource, similar to the [stack overflow comment you mentioned](https://stackoverflow.com/questions/28427339/how-to-implement-http-byte-range-requests-in-spring-mvc/63393094#63393094)
* Remove/check the relevance for the 'ETag' support (Now that we follow the spring boot framework more closely)
