### ISSUE TITLE
Cannot reset password for an EPerson created in Admin UI

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2988]
**Describe the bug**
If you create a new EPerson via the Admin UI (http://localhost:4000/admin/access-control/epeople), then it's impossible to set or reset a password for that user.

**To Reproduce**
1. Login as an Admin
2. Create a new EPerson (Visit "Access Control" -> "People" -> "Add EPerson" -> fill out data -> "Submit")
3. Notice that the form doesn't let you set an initial password
4. Now, logout
5. Attempt to reset the new User's password by clicking "Have you forgotten your password?" and entering the user email address.  (NOTE: If you are running DSpace locally, you may need to set `mail.server.disabled=true` so that you can see the text of the generated email in your `dspace.log` file.)
6. Click on or visit the generated forgot email page (http://localhost:4000//forgot/[randomuuid])
7. Attempt to set a password.  You'll receive a 400 error that says: `Attempting to replace a non-existent value (netID).`

The problem appears to be in this method: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/EPersonPasswordReplaceOperation.java#L99

That method *requires* that a password exists before it lets you reset your password.  (It also throws an incorrect exception that mentions "netID" which has nothing to do with the actual error.)

**Expected behavior**
There *must* be a way to set a user's password after creating them from the Admin UI.  

One of the following MUST be possible:
1. Either the Admin should be allowed to initialize a password when creating the user account
2. OR, a random password should be initialized for the user account (and shown to the admin or emailed to the user)
3. OR, it should be possible to reset a password _even if_ a password was not already set.

My slight preference would be for option 3, as it's in line with DSpace 6 (and it should require no changes to the Angular UI).  I'm not against the other options if there's a clear reason why we do not want a password to be reset when it's empty.

**Comment by benbosman** [comment]
The problem is that the request is a replace, e.g. `[{"op":"replace","path":"/password","value":"******"}]`, but you can't replace what doesn't exist

The potential solutions to approach this:
1. Send an add PATCH: the problem is that Angular can't know whether the value exists (whether it should be add or replace), and add is not implemented
2. Accept a replace even if no value exists. This doesn't impose any technical issues, but contradicts the concept of a replace. I'm assuming this will be used since it's the easiest solution.

Estimate includes tests

**Comment by tdonohue** [comment]
@benbosman : Sounds good overall.  After looking at your options & rereading our own contract docs on PATCH, it sounds like the _correct_ behavior here is to **always do an "add"**.  [According to our docs for "add"](https://github.com/DSpace/Rest7Contract/blob/main/patch.md#add)

> Please note that according to the JSON Patch specification RFC6902 a subsequent add operation on an already set attribute have the effect to replace the previous value.

So, it sounds like we might want to go with your _first solution_ & send an "add" no matter what.  If the value exists, then "add" should replace it.  Does that change the estimate here?  I'm assuming it also would require minor changes to the Angular UI to ensure an "add" is sent instead of a "replace".

**Comment by benbosman** [comment]
That's indeed a better solution. This would add the changes:
* Angular should send an add instead of replace: small change
* REST should support an add of the password (and possibly also still support replace, or only add): larger change
* When add is used, no value has to be present in REST
* All ITs should be adjusted to use add
