### ISSUE TITLE
process scheduler does not keep track of special groups

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#3040]
**Describe the bug**
Whenever a process is scheduled, information about user scheduling it is tracked. But we don't keep track of special groups, if any, active for the user at the moment of scheduling. 
In such cases, if scheduled process requires permission(s) related to a special group, it might fail. 

To provide a scenario if an user is granted as administrator by shibboleth, but he / she isn't administrator according to dspace systems, and with administrator grant can schedule a process, when the process is triggered and permissions are re-checked we do not have evidence of previous administrator grant.

**Comment by tdonohue** [comment]
@corrad82-4s : Excellent point.  This seems to be a flaw in the `Process` class/database table, as it only stores the `user_id` (EPerson UUID), and that doesn't include Special Group permissions assigned only when the user is logged in.

@KevinVdV or @benbosman : Could one of you take a closer look at this issue?  I'm debating myself whether this should be a part of beta 5, or if it's reasonable to push this to 7.1 as a "known issue" with Processes  (i.e. that you *must* be a direct member of the `Administrator` group in order to use Processes).  I currently lean slightly towards the latter, but I could use your advice/feedback here.

**Comment by tdonohue** [comment]
As Processes are currently limited to Site Admins in 7.0, this is lower priority for now. Pushing back to 7.3, or until it becomes higher priority.

**Comment by tdonohue** [comment]
On second thought, we may need to make Processes open to more users in order to implement various import/export tools needed for Community/Collection Admins.  Pulling this back into 7.1, flagging as `medium` for now.
