### ISSUE TITLE
Exception messages from a failed REST request are not properly displayed in the response

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/DSpace#3045]
**Describe the bug**
The response of a failed REST request won't include the message of the actual exception in the response, it'll be a generic message in the json with the actual exception's message only being shown in the stacktrace.

**To Reproduce**
1. Perform a GET request on the Items endpoint with a UUID that doesn't exist in the database
2. Verify that the "message" variable states "An exception has occured".
3. Verify that the trace shows a better, more precise message "core.items with id: ... not found"

**Expected behavior**
The message variable should state the proper more concise message so that the end user has a better idea of what went wrong

**Comment by tdonohue** [comment]
@Raf-atmire : This is expected behavior, as displaying Exception messages in REST responses is considered a minor *security issue*.  See for example, this explanation from LGTM.com: https://lgtm.com/rules/6780073/   (also look at the references linked at the bottom of that page).

You are correct that previously we had returned the exception message & stacktrace, but I changed this behavior in #2903 (and a few follow-up PRs).

While we are welcome to improve the error text returned in specific scenarios, I recommend *against* returning the exact error message.  So, for your example of the response of attempting to find an item with a UUID that doesn't exist, it sounds like that response is *improperly returning a 500* (which results in a generic "An exception has occurred") instead of returning a `404 Not Found`.

In any case, this ticket is too generic, so I'm closing it as "won't fix" as we won't return the actual exception text in the REST API.  Instead, I'd recommend logging ticket(s) to either fix the response code, or improve the message returned for a given response code (in our `DSpaceApiExceptionControllerAdvice` class, as shown in #2903).

**Comment by Raf-atmire** [comment]
@tdonohue I would like to bring further attention to this before we completely dismiss it.
The same issue arises when we try to delete an EPerson which is bound to a WorkflowGroup as the last remaining member. This should fail in the backend, as that is a restriction we put into the <a href="https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/eperson/EPersonServiceImpl.java#L285-L288">code</a>
However when we perform the delete call in the REST API for this EPerson, we get this as a response:
```
{
    "timestamp": "2020-11-10T10:15:57.609+0000",
    "status": 422,
    "error": "Unprocessable Entity",
    "message": "Unprocessable or invalid entity",
    "trace": "org.dspace.app.rest.exception.UnprocessableEntityException: Refused to delete user eb889c89-90fb-41d6-be80-ec999bede410 because it the only member of the workflow groupfa1a0f49-1d10-481d-97d9-8ecf3cbc6d7b. Delete the tasks and group first if you want to remove this user.\n\tat ...
    "path": "/server/api/eperson/epersons/eb889c89-90fb-41d6-be80-ec999bede410"
}
```
As you can see the 422 status is correct, the Entity is unprocessable due to this constraint, but the actual message doesn't give the end user any feedback as to what's actually wrong. (S)he is left guessing as to what exactly went wrong.
Now when we look at the trace (which is given in the entire response as can be seen above) this message IS present, so the end user could get the information from there, but it's largely hidden and the average user won't think about checking the trace of an error. This means that, for anyone actually trying to hack into the system or perform something nefarious, putting the complete reason in the message isn't more of a security issue than what's already present.

Due to these reasons, and the way that Angular had to work around this issue to actually retrieve a proper <a href="https://github.com/DSpace/dspace-angular/pull/874/files#diff-e3db7c7881bd2a078dc73168a7940a06386d2e263b0eeceb643ffd292310fbe5R56">message</a> I do believe we should consider this option further

**Comment by tdonohue** [comment]
@Raf-atmire : I'm sorry, but I disagree here.  I feel that exception messages should *not* be sent via the REST API for the following reasons:

* Per REST API best practices, we should rely more on HTTP Status Codes to communicate information to the client side & ensure the proper Status Code is thrown when an error occurs (e.g. ideally, 500 is rarely thrown, as it implies something went badly wrong & you need to check the logs).  While we can (where needed) enhance the basic message sent back with the status code, we should NOT be blindly returning the exception message as we cannot always predict what information it may include...and as noted, that can be a security issue.  Again, see https://lgtm.com/rules/6780073/ and also CWEs like https://cwe.mitre.org/data/definitions/497.html and https://cwe.mitre.org/data/definitions/209.html
* The meaning *behind* status codes (like your example 422 status) should be defined further in our REST Contract.  That specific example is documented in our REST Contract at https://github.com/DSpace/Rest7Contract/blob/main/epersongroups.md#deleting-an-eperson-group
* This *does* mean that clients (like the Angular UI) cannot rely on the error message returned to always be useful.  So, in some situations, the Angular UI might need to be modified to provide custom error messages based on its knowledge of the error code (for that specific request).  In your example of the 422 error during Group deletion, that's an invalid request that the Angular UI _should never make_.  But, in the case of a general 500, the Angular UI might provide a more user friendly error that says something like "An internal error occurred. Please ask your System Administrator to check the logs on the server for more information."

**So, overall, I do not agree that exception messages should be visible to clients.**  They should remain in the server logs only, and the client should only receive a status code. The client can use that status code (and the knowledge of what it means from our REST Contract) to provide more "user friendly" error messages / explanations back to the end user.

**Comment by tdonohue** [comment]
I've created a PR to remove the `trace` from these error responses by default: https://github.com/DSpace/DSpace/pull/3048  (Note however that you can easily re-enable it for development via your `local.cfg`)

**Comment by tdonohue** [comment]
We discussed this in today's meeting & decided the following:
1. By default no exception messages (or stacktraces) should be returned from the REST API
2. However, there are a few specific scenarios (like 422 errors) where some error codes do not provide enough information about how to resolve the error.
    * In these situations, we recommend create a custom Exception type.  For instance, when attempting to delete an EPerson which is the only member of a workflow group, we should throw a custom Exception (e.g. `EmptyWorkflowGroupException` or `EmptyWorkflowGroupAfterDeletionException` or similar) which perhaps extends `UnprocessableEntityException()`.
    * In [`DSpaceApiExceptionControllerAdvice`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/exception/DSpaceApiExceptionControllerAdvice.java), we can handle this unique Exception *differently*, so that it returns a more descriptive 422 error to the UI.
    * Ideally, the message returned to the UI is *translatable* (so it should ideally be pulled from `Messages.properties`), rather than just an English language Java error message.  (This might mean that the custom Exception needs to capture things like UUIDs or similar that may need to be passed to the i18n lookup as parameters.)
    * The more detailed error message can be returned in the `message` field in the REST Response.  The `trace` field will be disabled/removed in #3048 

So, overall, this ticket should remain closed as it is too general.  However, a new ticket can be created to create a custom Exception type for this 422 error so that it can return additional information to the UI.
