### ISSUE TITLE
Database configuration could be improved and better documented

### ISSUE THREAD

**Issue by J4bbi** [DSpace/DSpace#3070]
I am far from being an expert in databases or their configuration. The following observations should be taken as being meant to be constructive. I also appreciate that database pooling is almost exclusively a consideration for maintainers of DSpaces receiving high traffic.

DSpace supports two different database types, Postgres and Oracle.

Postgres is implicitly the recommended choice, it's [configured as default settings in local.cfg.EXAMPLE](https://github.com/DSpace/DSpace/blob/eafac164c86cb4e17f2ba3c1a623846ba7679c45/dspace/config/local.cfg.EXAMPLE#L75).

[Lines 97-108](https://github.com/DSpace/DSpace/blob/eafac164c86cb4e17f2ba3c1a623846ba7679c45/dspace/config/local.cfg.EXAMPLE#L97-L108) provide three different parameters: `db.maxconnections`, `db.maxwait` and `db.maxidle` that are passed directly to the DBCP2 DataSource bean instantiated by Hibernate when a `jdbc/dspace` JNDI connection is not found.

`db.maxwait`
DSpace config : "_Maximum time to wait before giving up if all connections in pool are busy (milliseconds)_"
DBCP docs: "_The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception, or -1 to wait indefinitely_."

This begs the question, what happens to the request that doesn't get a connection (what does giving up mean to DSpace?). If DBCP is to be taken seriously then an exception (SQLException?) is thrown. DBCP default is -1, unlimited whereas DSpace default is 5000.

There is a number of additional parameters that can be supplied to DBCP2 that should mitigate against databases running out of connections because of idling connections, I am especially curious about maxConnLifetimeMillis, an absolute limit to the length of a connection and timeBetweenEvictionRunsMillis which, if I understand correctly, runs a dedicated idle object evictor but there's also: validationQuery, removeAbandonedOnMaintenance, removeAbandonedOnBorrow. Is there any reason why these parameters should not be settable in the DSpace config?

The DBCP2 version being shipped with DSpace 6 is [2.1.1 from 2015](https://commons.apache.org/proper/commons-dbcp/changes-report.html#a2.1.1) From version 2.5.0 it requires Java 8 (JDBC 4.2). Current version is 2.8.0.

And we have not even begun to discuss the pros and cons of using DBCP versus the [Tomcat JDBC Connection Pool](https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html).

### As a side note
The [documentation for installation states that v. 9.4+ is needed for pgcrypto ](https://wiki.lyrasis.org/display/DSDOC6x/Installing+DSpace#InstallingDSpace-RelationalDatabase:(PostgreSQLorOracle)). In my opinion the Installation documentation should make more decisions for the reader. There should be a recommended stack of software for DSpace which IMO should be:

Postgres 9.5 at least (9.4 is not supported anymore)
Apache Tomcat 8, 8.5 or 9. (There are so many caveats for different issues with 7 for instance)

If a decision is made to have a recommended stack behind DSpace then that would simplify documentation greatly. Just a thought

**Comment by mwoodiupui** [comment]
I may have more to say later, but one thing caught my attention:

On Fri, Nov 27, 2020 at 04:04:12PM -0800, Hrafn Malmquist wrote:
[snip]
> ### As a side note
> The [documentation for installation states that v. 9.4+ is needed for pgcrypto ](https://wiki.lyrasis.org/display/DSDOC6x/Installing+DSpace#InstallingDSpace-RelationalDatabase:(PostgreSQLorOracle)). In my opinion the Installation documentation should make more decisions for the reader. There should be a recommended stack of software for DSpace which IMO should be:
> 
> Postgres 9.5 at least (9.4 is not supported anymore)
> Apache Tomcat 8, 8.5 or 9. (There are so many caveats for different issues with 7 for instance)

Tomcat 8+ makes the "overlay" method of local modification unreliable.
It may not work initially, or it may work initially and then stop
working after 'ant update' -- possibly after an unpredictable number
of 'ant update's.  It may start working again, seemingly at random,
after more updates.

Up through version 7, Tomcat sorts a directory by name when building a
classpath.  This behavior is not in the Servlet specification, and was
removed in Tomcat 8.  In Tomcat 8+, the classpath is constructed in
whatever order directory entries are returned by the filesystem.
Directory order is very difficult to predict or control, in some
filesystem implementations.  (We normally don't see this because 'ls'
and the shell sort entries by default.)

The "overlay" method relies on having 'additions-VERSION.jar' precede
dspace-*.jar in the classpath.  In Tomcat 8+ this condition is not
guaranteed, and the order can change whenever the directory is
updated.

We need to improve or retire the "overlay" method before recommending
Tomcat 8+.  This is a matter of some urgency:  the Tomcat 7.x EOL date
is 31-March-2021.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu

**Comment by tdonohue** [comment]
@mwoodiupui : The overlay issues with Tomcat 8+ and the "additions" module were already solved in https://jira.lyrasis.org/browse/DS-2437

@J4bbi : I'm not sure how to "resolve" this ticket as it seems more like a discussion.  I will note though that we tend to note the *minimal* requirements in our installation documentation.  That said, I'm perfectly OK with us saying something like "Postgres 9.4 or above (recommended v 9.5)" (as a simple example).  All these versions *have* been updated in the [DSpace 7 docs](https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace), but as you point out have not received updates in the [DSpace 6 docs](https://wiki.lyrasis.org/display/DSDOC6x/Installing+DSpace) since the 6.0 release.

In any case, flagging this simply as "needs discussion".  I'd recommend talking with the 6.4 release team about doc updates to make as part of the 6.4 release.

**Comment by J4bbi** [comment]
To be clear, I am part of the 6.4 release team (this is Hrafn Malmquist ;), and I have been updating the DSpace 6 docs. 

To give some context, we run DSpaces with Atmire's IRUS patch applied, about a week ago a couple of production servers became unreachable because of the maximum number of idle connections had been reached. In this case it we think the cause was a combination of network issues, very slow network, and the Atmire code not being resilient enough to handle such circumstances (see [here](https://github.com/atmire/IRUS/issues/4)). This led me to look pretty closely at how DSpace uses database pooling.

I was helped in part by @alanorth, who was experimenting with configuration because of the same problem three years ago (see [here](http://dspace.2283337.n4.nabble.com/Notes-on-PostgreSQL-connection-pooling-with-a-Tomcat-JNDI-resource-td4687149.html))

So, because database connection pooling is a context specific configuration, I am guessing there are quite simply, no one size fits all answers to the questions I have. I could put forward a PR to change configuration possibilities, I am already experimenting with that, but I thought it would be better to discuss first (I forgot to create a JIRA ticket, suppose it doesn't matter?)

I'll list here clearly my questions:

1. **Is providing DSpace with a preconfigured pool via JNDI seen as the better or more efficient way to set up a database connection?**

DSpace looks for the `jndi/dspace` preconfigured connection by default, this can not be switched off. DSpace will  "fall back to creating its own pool" if it doesn't find it. 

As @mwoodiupui and @alanorth have pointed out in the [Advanced Installation#External Database Connection Pool](https://wiki.lyrasis.org/display/DSDOC6x/Installing+DSpace#InstallingDSpace-Externaldatabaseconnectionpool) part of the documentation, using a JNDI pool brings much more granular control of parameters per webapp.

Using the DSpace configuration instantiated bean, each webapp and each CLI instance uses the same parameters.

Then the number of maxconnections is in fact:
total maximum connections = (_`db.maxconnection`_ * _[number of webapps_) + (_`db.maxconnection`_ * _[number of CLI commands running_)

This shouldn't then exceed the `max_connections` in the [Postgres Configuration](https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres). ?

There's clearly nothing wrong with skipping JNDI configured connections but my own experience when browsing through the Installation manual months ago was that setting it up was considered an unnecessary option.

But because to me at least, it is unclear whether all possible instances of DSpace webapps and CLI instances could result in an aggregation of connections exceeding maxconnections or max idle connections, for instance if a couple of cron jobs run and overlap and there is usage of several webapps at the same time....

2. **Why are only these three connection pooling settings configurable ?**

Apache Commons DBCP provides [several other configurable parameters](https://commons.apache.org/proper/commons-dbcp/configuration.html).


Parameter | Configurable in DSpace | Default | Description
-- | -- | -- | --
initialSize | N | 0 | The initial number of connections that are created when the pool is started.Since: 1.2
maxTotal | Y | 8 | The maximum number of active connections that can be allocated from this pool at the same time, or negative for no limit.
maxIdle | Y | 8 | The maximum number of connections that can remain idle in the pool, without extra ones being released, or negative for no limit.
minIdle | N |0 | The minimum number of connections that can remain idle in the pool, without extra ones being created, or zero to create none.
maxWaitMillis | Y | indefinitely | The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception, or -1 to wait indefinitely.
maxConnLifetimeMillis | N | -1 | The maximum lifetime in milliseconds of a connection. After this time is exceeded the connection will fail the next activation, passivation or validation test. A value of zero or less means the connection has an infinite lifetime.
softMinEvictableIdleTimeMillis | N | -1 | The minimum amount of time a connection may sit idle in the pool before it is eligible for eviction by the idle connection evictor, with the extra condition that at least "minIdle" connections remain in the pool. When minEvictableIdleTimeMillis is set to a positive value, minEvictableIdleTimeMillis is examined first by the idle connection evictor - i.e. when idle connections are visited by the evictor, idle time is first compared against minEvictableIdleTimeMillis (without considering the number of idle connections in the pool) and then against softMinEvictableIdleTimeMillis, including the minIdle constraint.
removeAbandonedOnMaintenance removeAbandonedOnBorrow | N | false | Flags to remove abandoned connections if they exceed the removeAbandonedTimout.A connection is considered abandoned and eligible for removal if it has not been used for longer than removeAbandonedTimeout.Creating a Statement, PreparedStatement or CallableStatement or using one of these to execute a query (using one of the execute methods) resets the lastUsed property of the parent connection.Setting one or both of these to true can recover db connections from poorly written applications which fail to close connections.Setting removeAbandonedOnMaintenance to true removes abandoned connections on the maintenance cycle (when eviction ends). This property has no effect unless maintenance is enabled by setting timeBetweenEvictionRunsMillis to a positive value.If removeAbandonedOnBorrow is true, abandoned connections are removed each time a connection is borrowed from the pool, with the additional requirements thatgetNumActive() > getMaxTotal() - 3; andgetNumIdle() < 2
removeAbandonedTimeout  N || 300 | Timeout in seconds before an abandoned connection can be removed.

I think more, possibly all configurable parameters should be configurable via DSpace. Why not?

First when I came across this issue with our production servers, I thought the three settings in the DSpace configuration were all that mattered.

3. **How have the defaults for the database connection pooling parameters been chosen**?
`maxWaitMillis` aka `db.maxwait` is set too 5000 by DSpace by default. Why was this number chosen? Default value is indefinite!! A quick Google for [how others configure this](https://javausecase.com/2017/01/22/how-to-configure-oracle-datasource-in-tomcat-9/) shows 10000! Is a relatively low setting of this property not likely to impact availability greatly?

The final note about the documentation was meant as a side note. I became a bit frustrated because there are different issues for different configurations.

**Comment by tdonohue** [comment]
@J4bbi : Thanks for clarifying the questions.  I still would flag this a `needs discussion`, simply because I don't think any of your (very good, well thought out) questions _have clear answers._  I'd also look to you & others who maintain DSpace sites on a daily basis for your expertise/recommendations here, as it sounds like our docs have become "dated" in this area.

That said, here's my immediate response to your questions:

> 1. **Is providing DSpace with a preconfigured pool via JNDI seen as the better or more efficient way to set up a database connection?**

My response to this sort of question is that it's hard to have a "one size fits all approach here".  Generally speaking, we try to have DSpace "easy" (or semi-easy) to install & get started with.  I suspect that's why JNDI is not documented as "the best way" is simply because it's an additional step, and small sites (which are still the vast majority of DSpace installs) may not really need it, as they don't have "significant user activity" to warrant it (so default pooling is "good enough"). 

However, if *many other* sites have found JNDI to be a better approach (and that's a question I'd ask to anyone finding this ticket), then maybe we should (1) document it more clearly, and (2) make it clear that many/most larger sites should be using JNDI.  So, I don't have the answer here, but it sounds like this needs feedback to make a decision.

> 2. **Why are only these three connection pooling settings configurable ?**

I suspect this is literally just because we didn't have a "need" for other settings at the time.  Many of these configurations were added 5+ years ago (maybe even much longer).  I'm not against adding more if it makes sense to do so (again, I'd look to everyone reading this ticket for advice here).

> 3. **How have the defaults for the database connection pooling parameters been chosen?**

Again, I suspect this is just a decision from long ago that needs re-analysis & re-thinking.  I don't know why those defaults were selected, but, based on you notes it sounds like we should change the current defaults to better align with "best practices" out on the web.

Thanks again @J4bbi for starting the discussion here.  It may still be useful to bring this up to the 6.4 team internally to get additional advice on how to update the docs.  Honestly, your ideas/questions make a lot of sense to me.  However, since I no longer manage/maintain DSpace sites myself, I cannot speak from any experience on what "works best"...therefore, I'd look to others to provide advice based on their experiences.
