### ISSUE TITLE
Exceptions in DSpace 7 REST API do not produce log entries in the DSpace log files

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/DSpace#3139]
**Describe the bug**
When an exception is thrown in the DSpace 7 REST API and it traverses to the `DSpaceApiExceptionControllerAdvice`, it will not produce a log entry in the DSpace logs by default. For example, when an UnprocessableEntityException is thrown due to a POST request on an Item, there will be no trace of this in the logs.

**To Reproduce**
1. Perform a request that's sure to throw an Exception (For example creating an EPerson with RegistrationData which contains an already in use email)
2. Verify that you get an error in your REST Response that shows a 400 Bad Request
3. Verify that you do not see any log entries for this Exception in the DSpace logs

**Expected behavior**
We should expect a log to show in the DSpace logs describing what went wrong at that given time. This will be useful for when REST Requests go south and we want to later identify what went wrong or what the culprit was.

**Comment by tdonohue** [comment]
@Raf-atmire : I'd recommend we *not* log all exceptions that occur in the REST API, as doing so could quickly fill up your logs with invalid requests. It also would allow for a strange sort of "attack" where someone could simply make the same invalid request over and over again against your REST API until the logs filled up all your available storage and the site crashes or becomes unresponsive.

Currently, the approach in `DSpaceApiExceptionControllerAdvice` is to only log 500 errors (Internal Server Error), as you can see right here: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/exception/DSpaceApiExceptionControllerAdvice.java#L179

I'm OK with us logging some additional exception types, but I'd hesitate to log anything that is an invalid syntax error or similar.   So, I'd hesitate to log most 4xx errors, as they can easily fill up the logs with useless information.  That said, I'm not against making exceptions for specific scenarios. We'd just need to discuss which scenarios really should be logged.

**Comment by mwoodiupui** [comment]
Log at different levels, perhaps?  5xx = ERROR, 4xx = WARN, with possible exceptions like 422 = ERROR.  Then you can control whether you monitor lesser issues, and turn them on and off as needed.

**Comment by tdonohue** [comment]
@mwoodiupui : Good point. That seems like an approach to consider.  I think we'd want to ensure any 4xx which are deemed `WARN` do not log the full stacktrace by default (as it's useless for many 4xx exceptions, as they are often a syntax error from the client). But, I'm fine with a single line WARN for most 4xx requests.

**Comment by tdonohue** [comment]
I'm going to move this into Beta 5, since we likely need some improvements here for 7.0 final.  I'd recommend we go with the approach laid out by @mwoodiupui with some minor tweaks:
* 5xx should be logged as `ERROR` with full stack trace (I think this is [already implemented](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/exception/DSpaceApiExceptionControllerAdvice.java#L179), as 500 seems to be the only 5xx error we currently throw from the REST API)
* 4xx should be logged as `WARN` with **no** stack trace (exceptions can be made for some specific messages if we feel a stacktrace is needed, or an ERROR is more appropriate, but those need to be discussed further).

Flagging this as needs an estimate.

**Comment by benbosman** [comment]
It can be implemented as a simple set of rules, e.g. the 5xx=ERROR etc as Tim suggested. I'd expect that to require 2 hours of work since no ITs are necessary

A more advanced solution would be to make it configurable which error codes are logged, at what level, with or without stack trace. I'd expect that to require 4 hours of work.

We can implement either solution, whatever the preference is

**Comment by tdonohue** [comment]
@benbosman : Sounds good. I'd recommend we go with the simple (2hr) approach for now.  If we find that is somehow limiting, we can enhance it later. So, for now, I think it's fine to mostly just make 5xx=ERROR (with stacktrace) and 4xx=WARN (no stacktrace).  If there are other specific responses where we feel a stacktrace is necessary (maybe 422), then those should be returned as ERROR as well.

Assigning back to you for your team to work on.

**Comment by tdonohue** [comment]
As discussed today, the upcoming PR for this ticket can be assigned to @abollini and @tdonohue
