### ISSUE TITLE
Statistics migration

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#3152]
**Describe the bug**
When using an existing DSpace installation, the statistics are lost in the migration to DSpace 7. This is due to the migration to solr 7

**Expected behavior**
Similar to the migration from DSpace 5 to 6, a migration should be included.
This migration should be tested on both DSpace 5 (old item IDs) and DSpace 6 (UUIDs)

**Related work**
https://github.com/DSpace/DSpace/pull/2058#issuecomment-471570536

**Comment by mwoodiupui** [comment]
Upgrading to DSpace 7 requires re-creating all cores:  `search` and `oai` by re-indexing, `authority` and `statistics` by dumping and reloading (since they cache data which are not recoverable from the database).  See https://wiki.lyrasis.org/display/DSDOC7x/Upgrading+DSpace#UpgradingDSpace-reload_solr steps 6 and 14.  The automatic in-place upgrade is no longer possible and has been removed.

**Comment by tdonohue** [comment]
@benbosman : This has been answered by @mwoodiupui above.  It's no longer possible to do this automatically in the latest versions of Solr, as Solr is no longer embedded.

So, I think this should be closed as "won't fix" as it's answered in the Upgrade docs, unless I'm misunderstanding the issue here?

**Comment by benbosman** [comment]
Yes, I hadn't seen this before
I haven't tested the procedure, but assuming it was tested on a DSpace 5 and 6, it should indeed solve the problem

**Comment by tdonohue** [comment]
Closing this as "won't fix".  At this time, I believe the upgrade instructions to be correct, as they were tested when the upgrade to Solr 7 happened (see PRs #2058 , #2393 and #2495 for that effort).
