### ISSUE TITLE
Using proxied request causes some responses mixed HTTP/HTTPS

### ISSUE THREAD

**Issue by vahem2lu** [DSpace/DSpace#3197]
When DSpace backend is configured on localhost/local IP and default port (http) and Apache proxy is being used to proxy requests to tomcat 

**To Reproduce**
1. Install DSPace and dspace-angular with default settings
2. Configure Apache to HTTPS and proxy requests to HTTP
```
  ProxyRequests Off
  ProxyPreserveHost On

  ProxyPass /server http://local-ip:8080/server
  ProxyPassReverse /server http://local-ip:8080/server

  ProxyPass / http://local-ip:4000/
  ProxyPassReverse / http://local-ip:4000/
```

**Expected behavior**
Response should include request URL and therefore not reply via http.

When using "view source" there seems that some of URLs are https:// and some are http://
```
<script id="dspace-angular-state" type="application/json">{&q;NGRX_STATE&q;:{&q;router&q;:{&q;state&q;:
output omitted
```

**Comment by tdonohue** [comment]
@vahem2lu : I'm closing this as "won't fix" as this looks (to me) like an incorrect ProxyPass setting.  When proxying requests from Apache (HTTPS) to Tomcat (HTTP), we'd **highly recommend** using AJP (https://httpd.apache.org/docs/2.4/mod/mod_proxy_ajp.html) instead of a simple HTTP proxy. 

Here's an example from some of our Docker development setups: https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker/dspace-shibboleth/dspace-vhost.conf#L93-L101

I believe that using AJP will solve the issue you are talking about (if I'm understanding correctly).
