### ISSUE TITLE
Features endpoint - features for the edit item page

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3201]
**Is your feature request related to a problem? Please describe.**
There are a number of features that would be useful to decide whether to enable/disable the various parts of the edit item page. Some of them are mentioned in [the spreadsheet we had](https://docs.google.com/spreadsheets/d/1182LcD_WqIZRbUGWpLtBw0aOMR9jhbOVB7GZqtTpR9A/edit#gid=0) others aren't.

**Describe the solution you'd like**
Add the following features:
- canManageVersions for an item
    - Currently there is a canSeeVersion and a canCreateVersion planned (neither of them are implemented yet). But on the versions tab you'd also be able to delete and update versions. So either we need canDeleteVersion and canUpdateVersion and we have to check all of them, or add a single canMangageVersions that checks all version operations in one go. I'd prefer the latter as that would be only one request instead of 4. But if we have reason to allow people on the page that can do some things and not others, we may need to split them up
- canManageBitstreams for an item:
    - For the same reasons as mentioned for versions, it would be good to have a single canManageBitstreams feature. And on an item, not on a bundle, as the currently suggested bitstream features. It is not practical to first check: can I create, read, update or delete  bundles on this item, and then for each bundle check the same for all the bitstreams on that bundle. That can lead to a lot of subsequent requests and slow page loads very quickly
- canManageRelationships for an item 
- canManageMappings for an Item
    - canManageMappedItems already exists for a collection, but there's also a mappings tab on the edit item page. I propose we rename it to canManageMappings and allow it on both items and collections.

For consistency we should also rename the withdrawItem and reinstateItem features to canWithdrawItem and canReinstateItem

**Comment by abollini** [comment]
> **canManageVersions for an item**
> Currently there is a canSeeVersion and a canCreateVersion planned (neither of them are implemented yet). But on the versions tab you'd also be able to delete and update versions. So either we need canDeleteVersion and canUpdateVersion and we have to check all of them, or add a single canMangageVersions that checks all version operations in one go. I'd prefer the latter as that would be only one request instead of 4. But if we have reason to allow people on the page that can do some things and not others, we may need to split them up

I agree. We can start with the single feature as we don't have yet an use case where some version can be deleted or updated and other no. 


> **canManageBitstreams for an item:**
> For the same reasons as mentioned for versions, it would be good to have a single canManageBitstreams feature. And on an item, not on a bundle, as the currently suggested bitstream features. It is not practical to first check: can I create, read, update or delete bundles on this item, and then for each bundle check the same for all the bitstreams on that bundle. That can lead to a lot of subsequent requests and slow page loads very quickly

In this case I would prefer to have a canManageBitstreams feature at the level of bundle, so that it is possible to give permission on the original bundle but not to the license or to a preservation bundle (for instance). As it is at the bundle level just a single call for each bundle is required that should not compromise the performance

> **canManageRelationships for an item**
I agree

> **canManageMappings for an Item**
> canManageMappedItems already exists for a collection, but there's also a mappings tab on the edit item page. I propose we rename it to canManageMappings and allow it on both items and collections.

I agree

For the changes above, including the canSeeVersion and the canCreateVersion and the corresponding tests **8 hours should be sufficient**. We can claim this task if needed

**Comment by tdonohue** [comment]
@abollini : Overall, this sounds fine...but I disagree on your analysis of `canManageBitstreams`. I don't **currently** see any real life use cases where we only allow management of some bundles/bitstreams and not others.  Technically, as you point out, it's possible to customize Bundles or Bitstreams to access restrict them further (so that you can only edit/delete specific Bundles or Bitstreams).  However,  if you have rights to *modify* the Item itself, then you can also easily **change** any permissions on a Bundle/Bitstream to allow yourself rights to manage it.

I also took a look at how we did this in 6.x & your scenario was never handled in DSpace 6.x code either. It looks like both the XMLUI & JSPUI only check if you had ADD/REMOVE on the **Item** in order to determine your rights on both all Bundles & all Bitstreams.

So, I worry we are overthinking this feature right now, and it'd be "good enough" to have an Item-level permission across all Bundles & Bitstreams.

That said, if you'd rather we rename this feature to be something like `canManageBundlesOfBitstreams` or `canManageBitstreamBundles` that might more accurately describe the feature.  The feature is more about whether you have the ability to add/modify Bundles and/or Bitstreams, either by creating a new Bundle, or by uploading a new Bitstream, or editing/deleting Bitstreams.  

So, overall, @abollini  your estimate sounds fine.  But, I agree with @artlowel that _for 7.0_ we likely only need a single check at the Item level.  We can always enhance this with more "fine grained" controls in 7.1 or 7.2, if we have a need to do so.

All that said, I'll add 8hours to this ticket & assign back to @abollini for his team to work on.  This task is obviously lower priority than all open PRs (both in terms of getting reviews done & updating your open PRs).
