### ISSUE TITLE
Need a way to identify withdrawn items via REST API (e.g. for tombstone page)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3245]
Required by https://github.com/DSpace/dspace-angular/issues/346

## Description
Copied from old ticket https://jira.lyrasis.org/browse/DS-4456 :

> In DSpace 6, when visiting a withdrawn item, the user receives a message stating the item is withdrawn. Admins will still be able to edit the item though
>
> In DSpace 7, regular users will receive a forbidden or unauthorized when visiting a withdrawn item. There's no way to identify whether the item was withdrawn or private.
>
> Since the forbidden or unauthorized is applicable, there's no JSON response to include that status. A response header may be used instead (similar to the response header of the login REST endpoint)

## Possible Implementation Ideas
Copied from @abollini 's comment to DS-4456: 

> Please note that this ticket should be only related to withdrawn item, private item are a different (confusing thing) see https://wiki.lyrasis.org/display/~bollini/DSpace+Item+state+definitions
>
> I spent some time searching for practice in other community without success... the 410 Gone status could seems an option at first glace but reading careful the specification and seeing how it is normally used it is NOT applicable in our situation because the withdrawn status can be temporary.
>
> I agree to go with a custom response header, it could be
> `X-DSPACE-WITHDRAWN: true`
>
> The response status should stay as is unauthorized, forbidden or ok for admins but if this make harder the client implementation we can reconsider that (BTW I expect that this would need just an "hardcoded" if before to trigger the authentication flow). Use always a 404 for non admin could lead to cache issues

**Comment by tdonohue** [comment]
Assigning this to you @abollini as discussed in today's meeting

**Comment by abollini** [comment]
Since the original discussion things have changed a bit so I want to suggest now an easier solution that should fit better with our current codebase.
The general idea is to allow everyone to retrieve a Withdrawn DSpace Item but include details about the Item only to administrators. To do that we should
1. relax the check in the org.dspace.app.rest.security.AuthorizeServicePermissionEvaluatorPlugin.hasDSpacePermission(Authentication, Serializable, String, DSpaceRestPermission) removing the withdrawn check
2. change org.dspace.app.rest.converter.DSpaceObjectConverter.getPermissionFilteredMetadata(Context, M) to check if the object to convert is a withdrawn item and filtering out all the metadata to non admin users
3. add/change tests as needed

this would take 3 hours (2-4 hours), you can assign to us if you wish

**Comment by abollini** [comment]
please note that the itemrest already has a flag to inform angular that the item is or is not withdrawn. So the problem was only about providing a tiny response instead than a 401/403

**Comment by tdonohue** [comment]
@abollini : Sounds good to me (both the suggested solution & the estimate).  Leaving assigned to you so that your team can begin work on this. Thanks!

**Comment by abollini** [comment]
@tdonohue here the PR for the rest contract https://github.com/DSpace/RestContract/pull/164
