### ISSUE TITLE
Can't save more than one bitstream's access conditions during submission

### ISSUE THREAD

**Issue by atarix83** [DSpace/DSpace#3279]
**Describe the bug**
While working on fixing https://github.com/DSpace/dspace-angular/issues/1119 I noticed that even if I add more than one access conditions to a bitstream added to a submission, the server save only one. Patch operation is sent properly by the client but the server response contains only the first access condition
```
[
   {
      "op":"add",
      "path":"/sections/upload/files/0/accessConditions",
      "value":[
         {
            "name":"openaccess"
         },
         {
            "name":"administrator"
         }
      ]
   }
]
``` 

**To Reproduce**
1. start a new submission 
2. upload a file (please mind the issues reported in the DSpace/dspace-angular#1110,  DSpace/dspace-angular#1121, DSpace/dspace-angular#1119)
3. start editing bitstream metadata
4. add an open access and administrator policy
5. save the bitstream form and check that only the first open access policy is present

**Expected behavior**
All the access conditions added to the bitstream should be saved

**Related work**
https://github.com/DSpace/dspace-angular/pull/1201

**Comment by tdonohue** [comment]
@atarix83 : thanks for the details. I agree that this seems like something we should fix immediately. @LucaGiamminonni : thanks for estimating this already.  The estimate looks reasonable to me.  Since this is a backend issue, I'll assign to @abollini  (as previously promised), but feel free to delegate to whomever is most appropriate at 4Science.
