### ISSUE TITLE
Scripts & processes error handling

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#3291]
**Describe the bug**
The command line script contains [System.exit(1)](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/scripts/handler/impl/CommandLineDSpaceRunnableHandler.java#L61), this ensures the script stops immediately
The REST script in the [same method](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/scripts/handler/impl/RestDSpaceRunnableHandler.java#L136) doesn't stop the script

This implies the `handleException` method works differently when used as a REST script, and the script will simply continue

**Expected behavior**
The [RestDSpaceRunnableHandler.handleException](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/scripts/handler/impl/RestDSpaceRunnableHandler.java#L136) should at least throw an exception so it stops from being executed

**Comment by tdonohue** [comment]
@benbosman : I'm struggling with where to put this as it's unclear (to me) whether this truly is a small ticket or not.  

It seems, to me, like we need to verify the "expected behavior" you listed above, as the thrown exception in that situation will occur on a task that is being run in the background (as these scripts run in the background when triggered from REST).  However, perhaps we could prove that by an IT or similar.

For now, I'll move this into the 7.0 board with "medium priority" and assign to you for an estimate.  But, based on the estimate, we may need to consider whether this can be safely delayed or not.

**Comment by benbosman** [comment]
Hi @tdonohue , I would estimate this can be solved with 4 hours of work (ensuring the script stops when an exception occurs, is left in a clear "FAILED" state, and has tests to prove this works

**Comment by tdonohue** [comment]
@benbosman : Sounds reasonable. I've added the estimate & assigned back to you for your team to work on. Thanks!
