### ISSUE TITLE
Dspace image running as root not safe 

### ISSUE THREAD

**Issue by Akshay-Hegde** [DSpace/DSpace#3310]
https://github.com/DSpace/DSpace/blob/0cfe4d068657a88cb47d35ec364ccd853ac8d56c/Dockerfile

Recently I tested dspace 6x and 7 images, however noticed below directory permissions are `root:root` which is really not safe, probably in future builds may be improved.

This is already known issue: https://forums.docker.com/t/user-only-affects-permission-of-immediately-following-copy/2065

```
/dspace
/usr/local/tomcat
```
Probably below may help

```

...
...
FROM tomcat:8-jdk11
ENV DSPACE_INSTALL=/dspace
COPY --from=ant_build /dspace $DSPACE_INSTALL
EXPOSE 8080 8009
```
to
```
...
...
FROM tomcat:8-jdk11
RUN addgroup --gid 1000 dspace && useradd dspace -u 1000 -g 1000 -s /bin/bash -d /dspace
ENV DSPACE_INSTALL=/dspace
RUN chown -R dspace:dspace /usr/local/tomcat /dspace 
RUN chmod g+s /dspace /usr/local/tomcat
COPY --chown=dspace:dspace --from=ant_build /dspace $DSPACE_INSTALL
EXPOSE 8080 8009
```

Also for solr 

```
ReadWritePaths=/path/to/solr/data
```

**Comment by tdonohue** [comment]
@Akshay-Hegde : Please keep in mind, **these Docker Images are NOT meant for Production**. We only use them for development/testing purposes, which is why we have not paid any attention to creating secure images at this time.  See this newly added warning here: https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker-compose/README.md

That said, it sounds like you've already done some work on getting these images secured.  If you wanted to submit a Pull Request with your fixes, we could review the fixes & consider including them in the main codebase.  Thanks!

**Comment by Akshay-Hegde** [comment]
Sure, thanks for the info since there were know issue with `USER` I thought may not have noticed, so I just posted. Soon I will modify Dockerfile and share for review.

**Comment by tdonohue** [comment]
Closing as this is outdated now.  In DSpace 8 we use embedded Tomcat instead of the Tomcat Docker image.  So, this is fixed as of DSpace 8.
