### ISSUE TITLE
CanManageMappingsFeature sometimes does not respond as expected

### ISSUE THREAD

**Issue by alemarte** [DSpace/DSpace#3315]
**Describe the bug**
The `CanManageMappingsFeature` sometimes does not respond correctly both affirmatively or negatively.

**To Reproduce**
To reproduce the issue run the related angular PR code https://github.com/4Science/dspace-angular/tree/CST-4319 and follow detailed steps described by @tdonohue in his review [comment](https://github.com/DSpace/dspace-angular/pull/1250#pullrequestreview-694358433).

**Expected behavior**
The `CanManageMappingsFeature` when the object is an Item, should respond true if the user is admin or has submission rights over at least one alternative collection, and false otherwise.

**Related work**
https://github.com/DSpace/dspace-angular/pull/1250

**Comment by alemarte** [comment]
@tdonohue we've spent 2 hours to fix it and we can open the PR

**Comment by tdonohue** [comment]
@alemarte : Is there a PR ready for this? I'd love to be able to test it today alongside the frontend PR (I'm out of the office all of next week, so if it's not ready today this will need a different volunteer).

In the meantime, I'll pull this ticket into the 7.0 board, since it's necessary to get DSpace/dspace-angular#1250 working.

**Comment by abollini** [comment]
The issue is mostly due to a discrepancy between how the feature "check" is implemented and how action is really performed.

More specifically, the "check" is currently close to what was the implementation in version 6: the user needs to have ADD & WRITE permission on the collection and READ on the ITEM
