### ISSUE TITLE
We should remove the --optimize feature of 'dspace stats-util'

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#3331]
**Describe the bug**
The so-called "optimization" of Solr cores is contrary to current advice from Solr's maintainers.  We shouldn't make it easy to do the wrong thing.  This option should be removed.

**Comment by tdonohue** [comment]
This seems reasonable to me. It's low priority, but adding to 7.1.  If we don't get to it then, we'll move to a later release.

**Comment by alanorth** [comment]
Oh, I'm surprised to see that the optimize flag still exists here! It was removed from our `index-discovery` command years ago. There was a lot of discussion on the dspace-tech mailing list and Jira (now defunct) at the time. It has been commented out in my repository's scheduled tasks since 2016.

Some other references:

- See comments on the DSpace 5.x wiki page for [Scheduled Tasks via Cron](https://wiki.lyrasis.org/display/DSDOC5x/Scheduled+Tasks+via+Cron)
- See upstream Solr issue from 2012 (!): https://issues.apache.org/jira/browse/SOLR-3141
