### ISSUE TITLE
Error with setting up Dspace backend

### ISSUE THREAD

**Issue by abdbuzurg** [DSpace/DSpace#3361]
I am trying to set up Dspace in my local environment. There was no problem setting up the frontend part of the app. However, when I am trying to set up the backend part there is an issue that I am currently facing with the **ant fresh_install**. 

![1](https://user-images.githubusercontent.com/45818668/129028792-2d5648b9-53ab-489d-be16-8f5e750d3b8f.PNG)

Let me know if you know how to solve this issue.

**Comment by tdonohue** [comment]
@abdbuzurg : That appears to be a bug from *Apache Ant* and not DSpace.  The key error is this one...:
`CreateProcess error=206, The filename or extension is too long`

If you google that, it sounds like that error means that your CLASSPATH is too long for Windows to handle.  So, it might be fixed by simply shortening your really long directory path starting with `C:\Users...`  In other words, move DSpace up to C:\DSpace or similar might be a quick fix.  You also might want to check your CLASSPATH environment variable to see if there's anything you can remove from there.

Closing this as answered.  If you have further questions, please use one of the recommended support options at https://wiki.lyrasis.org/display/DSPACE/Support
