### ISSUE TITLE
Misssing Javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [DSpace/DSpace#3367]
Hello! I find in your [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide) that 
> Write Javadocs for public methods and classes. Keep it short and to the point.

However, I still witness some likely missing Javadoc for public methods and classes in the following files:
* dspace-rest/src/main/java/org/dspace/rest/RestIndex.java
* dspace-swordv2/src/main/java/org/dspace/sword2/VerboseDescription.java
* dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SearchResultsRest.java
......

Would you like to add Javadoc for these methods, or they are just not that important?
If there is anything I can help with?

**Comment by mwoodiupui** [comment]
Good documentation is always welcome.  And much is missing, and much else could be greatly improved.  The style guide was written long after some of the code in DSpace.  And bits like the old REST API and SWORD have not received much attention since then.

Often, when I have to puzzle out what some supporting code is doing while writing a patch, I'll take a moment to put what I've learned into the Javadoc that I wish had already been there.

**Comment by tdonohue** [comment]
@CoolKangaroo2022 : as @mwoodiupui correctly notes, some older methods are missing JavaDocs as they were created prior to the style guide.  If you'd like to help us add missing JavaDocs, we'd welcome the contributions (just create a Pull Request for us to review).  Otherwise, we do our best to update/correct JavaDocs little by little in new PRs -- but there's no one specifically working on adding missing JavaDocs at this time.

**Comment by tdonohue** [comment]
Closing as an 'answered' question.  JavaDocs changes always recommended/accepted.  However, I don't see a need to create tickets for every place where JavaDocs is lacking (as that'll just be a ton of tickets).  No ticket necessary, just create a PR if you want to help improve JavaDocs!
