### ISSUE TITLE
[DS-3296] REST API returns 500 instead of 404 for missing item

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6651]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3296">[DS-3296]</a> created by ari</i>
<p>When item is not found, API returns server error:<br/>
<a href="https://demo.dspace.org/rest/items/something_invalid" class="external-link" target="_blank" rel="nofollow noopener">https://demo.dspace.org/rest/items/something_invalid</a><br/>
returns 500 (internal server error) but AFAIK the correct code would be 404 (not found)</p>

<p>DSpace tries to parse UUID that is not valid. This leads to server error instead of 404 (not found) code. Discussion with answer by Peter Dietz:<br/>
<a href="https://groups.google.com/forum/#!topic/dspace-tech/lLWemprc6w8" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/dspace-tech/lLWemprc6w8</a></p>

**Comment by minurmin** [comment]
Considering that invalid UUID can be intepreted as client error, I propose (#8346) that 400 Bad Request* return status should be used instead of 404 (with current DSpace 6.x codebase missing items are already handled correctly, provided that the client provides syntactically valid UUID). 

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by tdonohue** [comment]
Closing, the old (v6) REST API is no longer being actively developed and will be removed in 8.0 (see #7643).  The new REST API v7 is the current REST API: https://github.com/DSpace/RestContract/#readme
