### ISSUE TITLE
Switching submission collection during workflow does not work

### ISSUE THREAD

**Issue by f-rapp** [DSpace/DSpace#7965]
**Describe the bug**
Switching the submission collection during workflow does not work.

**To Reproduce**
1. Login as administrator.
2. Take a task from the task pool and try to change the collection.
3. ![grafik](https://user-images.githubusercontent.com/67266996/134893529-4ee3c7b8-df10-463f-a954-78c5335a158c.png)

**Expected behavior**
The workflow item should change its owning collection to the collection selected in the dropdown.

**Related work**
https://github.com/DSpace/dspace-angular/issues/1234

**Comment by abollini** [comment]
Collection change in workflow is not trivial. The collection could have different workflow definition associated or also if the same workflow definition is used it is possible that the flow will change due to custom workflow steps.
A first "workaround" would be to disable the feature in workflow and allow to change the collection only during the submission (workspace phase)
