### ISSUE TITLE
Profile page doesn't show "special groups" in the "Authorization groups you belong to" section

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#7978]
**Describe the bug**
When you configure users to have a special group this special group doesn't show up in your profile page.

**To Reproduce**
* On a server where shibboleth is enabled add the following to your configuration:
    - authentication-shibboleth.default-roles=DSpace
    - authentication-shibboleth.role.DSpace=Test group
* Make sure to create the "Test group" on your system after
* Authenticate using shibboleth
* Go to the profile page, the "Test group" isn't displayed. 

**Expected behavior**
The "Test group" should be displayed here. This is because the EPersonGroupLinkRepository just calls on eperson.getGroup() instead of groupService.allMemberGroups(context, eperson).

**Comment by mwoodiupui** [comment]
May I suggest that Special Groups be listed separately and clearly marked as something different.  One does not configure *users* to be in a Special Group; these memberships are properties of the *session*, granted by the particular authentication method used for the session.  There is quite a bit of confusion about the nature of Special Group membership, and we would do well to carefully distinguish these memberships whenever they are displayed.

I could argue that Special Groups should *not* be displayed on the profile page, since membership is not a property of the user account.  I did not, because I can't think of where we display properties of the session.

**Comment by KevinVdV** [comment]
@mwoodiupui Just to clarify the use case I had with one of my clients, I configured some shibboleth roles & wanted to test that when logging in the user is indeed assigned to these groups. I then noticed that the profile page didn't display the group. Leading me on a wild goose chase until I ended up realizing that the groups just weren't displayed there.

Not saying they need to be displayed under the "Authorization groups you belong to" section, but they should be displayed somewhere on this page.

Giving this a bit further thought, IF you have an indirect group membership these also won't be displayed here, not sure what we want to do with those.

**Comment by tdonohue** [comment]
Moved this into 7.2 with `medium priority` for now. At the very least we likely should display special groups in a different section on that page.  This may require changes to both the backend and frontend.  Also flagged as `help wanted` to note that this could be done earlier by a volunteer.

**Comment by tdonohue** [comment]
Duplicated by #8206 , which was fixed in 7.3 by #8276 and DSpace/dspace-angular#1634.  So, this is fixed already.
