### ISSUE TITLE
7.0 REST endpoint /api/submission/workspaceitems

### ISSUE THREAD

**Issue by mtrojan-ub** [DSpace/DSpace#8024]
**Describe the bug**
Whenever trying to use this endpoint (within https://api7.dspace.org/server), i just get a HTTP error code 400 (Bad Request) without receiving any specific error information (neither as HTTP header nor inside the response body). 

It's hard to figure out which parameters to use, because the documentation seems to be inconsistent with the REST API tutorial. For example, when passing a collection id, the endpoint documentation says that you should use a parameter called `owningCollection`, but due to the tutorial you should use a parameter called `parent` for the same purpose:
- https://github.com/DSpace/RestContract/blob/main/workspaceitems.md
- https://dspace-labs.github.io/DSpace7RestTutorial/exercise5#2a-creating-a-workspaceitem

Also, the example PDF file referenced in the tutorial does not exist:
https://github.com/DSpace/DSpace/blob/master/dspace-spring-rest/src/test/resources/org/dspace/app/rest/simple-article.pdf

I tried to use this endpoint to upload a PDF file in multiple ways (e.g. as multipart/form-data or text/uri-list), but it worked neither way.

**To Reproduce**
1. Try to submit a PDF file via the /api/submission/workspaceitems endpoint

**Expected behavior**
Either a correct submission, or a failed submission with specific information about the reason why it failed (if there is a 400 "Bad Request" error code, there should be some additional information provided somewhere, either as HTTP header or inside the response body. Or there should be a more specific error code.)

**Comment by tdonohue** [comment]
@mtrojan-ub : By default the REST API never returns the full exception text (as that can be a security issue).  But, the exception should be logged (in dspace.log).  You can also enable debug mode in the REST API, which tells it to return the full exception in the response. See https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DebugmodefortheRESTAPI(optional)

Unfortunately, the [REST Tutorial](https://dspace-labs.github.io/DSpace7RestTutorial/) is outdated & could use some updates. The more official docs are the REST Contract at https://github.com/DSpace/RestContract/blob/main/workspaceitems.md  However, it's possible something there needs cleanup.

I think it'd help us if you could provide the full error message you receive, as it's possible this isn't a bug but simple a configuration or documentation issue.  See our Troubleshoot an error guide for hints on finding the error message: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

**Comment by mtrojan-ub** [comment]
@tdonohue: Thanks for the hints! We are still about to install our own DSpace 7 test server. As soon as we got it, we will enable the settings and provide additional information.

Another important aspect is that i am trying to use the API from a self-written PHP client. So it might as well be some incorrect Content-Encoding sent by the client or anything similar to that.

**Comment by tdonohue** [comment]
Closing for now, as I suspect this is a configuration issue (or invalid command sent to REST API).  But, if it's discovered that there's a bug, we can always reopen as needed.

**Comment by tdonohue** [comment]
@mtrojan-ub : That error seems to be saying you tried to submit content using an account that does not have submit access on _any collections_ in the system.  Here's the line of code throwing the error: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/WorkspaceItemRestRepository.java#L249

You need to make sure the user account has "ADD" permissions on a Collection by adding that user to a Collection's group of Submitters. This is often easier to achieve through the UI, but you could watch those UI steps to "watch" the requests it sends to the REST API and then model those same requests in whatever you are using to call the REST API.

The behavior in this case isn't the best from the REST API... we probably should throw a 403 (or 401) permissions error, instead of the 400.  But, the fact that an error is thrown is correct...it sounds like the request is invalid in some way.

**Comment by mtrojan-ub** [comment]
This turned out to be a HTTP header problem. We thought that after logging in, sending the Cookie again would be enough, but instead we had to send the Authorization header within each request. Maybe that's why the permissions and collections could not be checked properly. Also, our server admin fixed a problem within the apache configuration to get rid of another internal server error.

Thanks a lot for your help!

**Comment by tdonohue** [comment]
@mtrojan-ub : Glad you figured it out!

Just for the record & in case anyone else stumbles on this same thing... this is **expected behavior**.  The `Authorization` HTTP Header MUST be included in every request after login in order for each request to be authenticated.  See REST Contract docs at https://github.com/DSpace/RestContract/blob/main/authentication.md#username-password-based-authentication
