### ISSUE TITLE
Error validating authority required input in submission

### ISSUE THREAD

**Issue by PabloDeAlbu** [DSpace/DSpace#8041]
It is not possible to deposit a submission form with authority-controlled entries.

Once the fields are completed and the form is saved, this notification appears and despite having completed the fields, the item cannot be deposited.

![Captura de pantalla de 2021-11-25 10-54-05](https://user-images.githubusercontent.com/11927172/143455023-7b12daf6-567f-45ca-be7c-098b36258ffd.png)

![Captura de pantalla de 2021-11-25 11-11-07](https://user-images.githubusercontent.com/11927172/143456445-3d074037-a8ba-4c54-a38d-e88a27233dcc.png)

The problem seems to come from the authority-controlled metadata validation in https://github.com/DSpace/DSpace/blob/c2e31d08ef10b4cd2e3dd1853f18d1f06c7dbe25/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/MetadataValidation.java#L83-L84.

**To Reproduce**
1. Configure a metadata to be authority required in your local.cfg
2. Start a submission
3. Complete the requiered inputs and save

**Expected behavior**
The item should be able to be deposited

**Related work**
https://github.com/DSpace/DSpace/pull/8034

**Comment by tdonohue** [comment]
@PabloDeAlbu : Is this bug fixed by your separate PR #8034?  It looks, to me, like you've fixed this exact line of code in your #8034.   If your PR is the fix for this bug, then I can link them up (or you can do so by simply editing your PRs description and  adding `Fixes #8041` somewhere in the description)

If this is a separate bug from #8034, then it'd be good to describe this bug in more detail...the description above sounds almost identical to what you've noted in #8034 already.

**Comment by PabloDeAlbu** [comment]
@tdonohue PR #8034 fix this bug. I' ve already changed the PR description.
