### ISSUE TITLE
assetstore folder missing

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/DSpace#8073]
With the normal install the assetstore folder is missing, and no upload works.

**Comment by tdonohue** [comment]
@WolfgangT71 : Not enough information is provided in this ticket for us to reproduce the problem.  We'd minimally need the version of DSpace along with how you installed it to better understand the issue. 

Since we've not heard of this issue yet, I'd immediately suspect it may be an environment or configuration issue.  It's possible the "ant fresh_install" command you must run on your backend was forgotten or threw an error, as that's the command that creates the assetstore folder.  See step 9 in https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-BackendInstallation

If you are having issues with your DSpace installation, I'd also highly recommend using one of the Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by WolfgangT71** [comment]
Installed version 7.1 exactly after the instructions on a debian 11 system.
The folder was not in [dspace] after 
`ant fresh_install`, I had to manually create it.

**Comment by WolfgangT71** [comment]
To my knowledge it did not throw an error, and I did not forget to call, actually I even called it twize, as I made some changes on the backend.

**Comment by WolfgangT71** [comment]
Only found out with assetstore, after I tried to upload an item. So the install was two das ago.

**Comment by tdonohue** [comment]
Unfortunately, I'm not able to reproduce this.  It appears that the Assetstore folder is now created automatically by our code in `DSBitstoreService` (which is called by `BitstreamStorageServiceImpl`) based on the value of "assetstore.dir" in configuration.

Because of that, this would mean that the user running Tomcat would need permissions to *create* the `assetstore.dir` on the filesystem.  If they do not have those permissions, then the directory may not be created.  So, I'd recommend double checking those permissions & if you are still having issues, ask for more help via one of the Support options: https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by Dnyamwamu** [comment]
I guess you should first activate the assetstore configuration in 'dspace.cfg'. Search for 'assetstore.dir=....' and Uncomment that line. By default the assetstore directory will be created inside '/dspace/assetstore'
