### ISSUE TITLE
Permanent URI not correct

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/DSpace#8079]
**Describe the bug**
I checked it is not existent inside the demo7.dspace.org demo.
So perhaps it is only a misconfiguration from me, but please help.

By the server/oai the links have 8080 in it, also then it does not work, not sure where this is set wrong.

Perhaps an apache or Tomcat setting which went wrong. I'm using Letsencrypt en rewrite everything to SSL.

By dspace angular, when checking the permanent links in collections.
The permanent linktext is shown correct.
https:/my.dspace.domain/handle/123456789/5 But the link  https:/my.dspace.domain/my.dspace.domain/handle/123456789/5 is wrong.

As I checked now the page source code, it is clear that it is not a DSPace error, just a missconfiguration of Apache or Tomcat.

But the real funny thing:

`<a _ngcontent-dspace-angular-c221="" href="https:/my.dspace.domain/handle/123456789/5">https:/my.dspace.domain/handle/123456789/5</a>`

But when i hoover over the link in the source code:

`https:my.dspace.domainhttps:/my.dspace.domain/handle/123456789/5`

Rewrite in Apache2
```
RewriteRule http://my.dspace.domain:8983 http://my.dspace.domain:8983 [R=301,S=1,PT,L]
RewriteCond %{SERVER_NAME} my.dspace.domain
#RewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

In tomcat I use this connector

```
<Connector port="8080" protocol="HTTP/1.1"
               minSpareThreads="25"
               enableLookup="false"
               connectionTimeout="20000"
               redirectPort="8443"
               disableUploadTimeout="true"
               URIEncoding="UTF-8" />

```

If you need anything else feel free to ask

**Comment by tdonohue** [comment]
@WolfgangT71 : This sounds like a misconfiguration of your DSpace.  The URLs you reference all have a single slash "/" after `https:` (i.e `https:/` instead of `https://`)...which implies one of your configurations in `local.cfg` on the backend may be missing that same slash.

So, rather than `https:/my.dspace.domain/handle/123456789/5` the URL should be `https://my.dspace.domain/handle/123456789/5

I checked the demo site, and all these URLs are working there. See for example https://demo7.dspace.org/entities/book/db417fce-088d-40c2-983d-bbc95917ce88

If you need additional DSpace support, please see https://wiki.lyrasis.org/display/DSPACE/Support
