### ISSUE TITLE
bitstreams endpoint URL documented by the HAL browser results in a whitelabel error

### ISSUE THREAD

**Issue by hardyoyo** [DSpace/DSpace#8085]
**Describe the bug**
The Bitstreams endpoint [1] documented by the HAL browser [2] produces a whitelabel error.

1. https://api7.dspace.org/server/api/core/bitstreams
2. https://api7.dspace.org/server/#/server/api

**To Reproduce**
1. Go to the API7 demo server [1]
2. Observe the list of endpoints in the response body
3. attempt to visit the bitstreams endpoint [2]

**Expected behavior**
A list of bitstreams, with more documentation on how to use the endpoint. 

**Related work**
Link to any related tickets or PRs here.

**Comment by hardyoyo** [comment]
according to this https://github.com/DSpace/RestContract/blob/main/bitstreams.md the bitstream endpoint is "unsupported"

I suppose this issue should actually be to remove the unsupported endpoint?

**Comment by tdonohue** [comment]
@hardyoyo : Answered via Slack.  This endpoint works, but it only supports accessing a *single Bistream at a time*.  So, for example, you MUST access `/bitstreams/[uuid]`, as documented here: https://github.com/DSpace/RestContract/blob/main/bitstreams.md#single-bitstream

The root endpoint `/bitstreams` is the REST way of saying "Give me every single Bitstream in the system".  We chose not to support that feature, as you normally access a Bitstream via an Item -> Bundle -> Bitstream linkage.  So, that's why `/bitstreams` throws an unsupported error, while `/bistreams/[uuid]` works fine.

Closing, as this is expected behavior. But, definitely let us know if you have more questions about this.
