### ISSUE TITLE
General stability issue

### ISSUE THREAD

**Issue by MarisArins** [DSpace/DSpace#8094]
Hi, please no stones throwing for lack of proof or good details on this one.

What happens : 
Sometimes navigation or and activity can cause the app to hang.
How it looks : 
you click to navigate to different page, or want to perform a search or submit new item and the "process" remains eternally on "busy indicator"
What is known about conditions:
Nothing, probably that is the most describing symptom ! After an action the hangs there is no console logs, nor it triggers any REST calls.

It looks like angular "store" (pardon my ignorance) swallows the action right after presenting busy indicator.

Additional details: 
This can happen couple minutes after starting your work session, or it  can happen after prolonged time including some user inactivity, but I have never seen it happen in first "clicks" of user session, so there might be a time factor involved.

**Comment by MarisArins** [comment]
sorry, this must be under dspace-angular project...

**Comment by MarisArins** [comment]
In recent testing I have seen the UI "hanging" on demo site twice in following situation (by far not every time I do this it happens):
I create a new collection and after it is added I click on breadcrumb navigation to go to parent community, in result UI hangs. That has happened 2x in last day.

**Comment by firoball** [comment]
Have you checked the dspace.log of backend?
Usually when "hanging UI" with loading dots happens to me, I find that a related exception was thrown. This causes whichever action was triggered through frontend to not finish, leaving the frontend in "hanging" state.

**Comment by MarisArins** [comment]
Thanks for hint @firoball, UI just hang for me again, I looked at backend logs following your advice, but I did not found any error messages there.

On UI in the console I had this error log, not sure if it is a cause or result, most probably result:

core.js:6210 ERROR Error: Uncaught (in promise): EmptyError: no elements in sequence
    at resolvePromise (zone-evergreen.js:798:1)
    at resolvePromise (zone-evergreen.js:750:1)
    at zone-evergreen.js:860:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:28578:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at drainMicroTaskQueue (zone-evergreen.js:569:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484:1)
    at invokeTask (zone-evergreen.js:1621:1)

Now when it is "hung", I can get the error out in console every time I am trying to induce navigation.

The error happened in following situation:

- I log in and open submission form
- I wait for long time (not sure how much, but could be ~20min)
- I am leaving submission form by navigation (in this case clicking logo that leads to /home)

**Comment by tdonohue** [comment]
If this issue is still occurring, I'd recommend following the Troubleshoot an error guide to try and debug what may be occurring: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

We are not experiencing this sort of issue on our demo site (demo7.dspace.org) and haven't heard reports of this sort of regular instability in DSpace 7.3.  So, I suspect there is an underlying error that is causing this, or some sort of misconfiguration.

I'm going to close this ticket as "won't fix" as I don't think this is actionable at this time.  But, I'd encourage you to create a new ticket if you find an exact, reproducible bug.  Or, if you find a more descriptive error message, please use one of our Support channels to get additional help: https://wiki.lyrasis.org/display/DSPACE/Support
