### ISSUE TITLE
Full support for Java 17

### ISSUE THREAD

**Issue by jeffmorin** [DSpace/DSpace#8190]
The DSpace codebase was made “build-compatible” with Java 17 in release 7.2, that is, it can now be built using a JDK 17. However, it must still be built towards Java 11, which is reflected by the `java.version` property and the maven-compiler-plugin `release` argument.

The project should be fully Java 17 compliant, which would result in being able to build it towards Java 17, which is the latest LTS Java version since September 2021. This would allow DSpace users/developers to write code using newer Java features (e.g., string blocks, switch expressions, records) for their own needs. Such code, however, should not become part of the DSpace codebase as long as DSpace is expected to support Java 11.

In a local copy of the version 7.2 codebase, I upgraded a few library versions (e.g., Spring, JSON-Path) and marked several injected dependencies with `@Lazy` to make the project buildable and runnable again. I consider the `@Lazy` annotations a temporary fix, as the involved classes and attributes should be refactored to eliminate all circular Spring bean dependencies.

The resulting code is still fully compatible with Java 11. It can be switched to any Java version between 11 and 17 (inclusive) by setting the `java.version` property and maven-compiler-plugin `release` argument mentioned above accordingly.

**Comment by tdonohue** [comment]
@jeffmorin : If you have dependency updates and code refactors that align the DSpace codebase more with JDK 17, I think we'd welcome those.  However, at this time, I think we need to retain JDK 11 compatibility -- simply because JDK 17 is so new, and we'd need to gather broader feedback before considering a major switch from JDK 11 to JDK 17.

That all said, we'd welcome PR(s) which provide code changes to better align the codebase with JDK 17, provided that those changes are also still JDK 11 compatible.  So, you are welcome to submit your work as a PR whenever you have the chance, and I'll work to get it assigned to reviewers and considered for inclusion in the next 7.x releases (7.3). Thanks!

**Comment by tdonohue** [comment]
This appears to be fixed as of 7.3 in #8215.  See comments in https://github.com/DSpace/DSpace/pull/8191#issuecomment-1112269489
