### ISSUE TITLE
Deprecated DS 6 REST API interferes with DS 7 'special groups' on login

### ISSUE THREAD

**Issue by BrandonKowalski** [DSpace/DSpace#8201]
**Describe the bug**
I am using DSpace 7.2 with the DS 6 REST API installed.

When the REST API is installed, backend does not find special groups from Shibboleth login.

I've done a few hours of troubleshooting and have identified the issue. 

When the deprecated API is installed, the login flow uses the following class [EPersonRestAuthenticationProvider.java](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestAuthenticationProvider.java) instead of [DSpaceAuthenticationProvider.java](https://github.com/DSpace/DSpace/blob/main/dspace-rest/src/main/java/org/dspace/rest/authentication/DSpaceAuthenticationProvider.java). The former makes no calls to find the 'special groups'.

Removing the deprecated API solves this issue but this is problematic as my institution will continue to rely on these legacy APIs until our teams develops against the new API.

**To Reproduce**
1. Install DS7 with the Deprecated DS 6 REST API
2. Configure Apache with Shibboleth and AJP proxy to DS 7
3. Configure DS7 with the appropriate local.cfg settings to find the Shibboleth roles
4. Add the group to DS 7 that matches the name listed in the config from step 3
5. Sign in with Shibboleth and observe that special groups are not applied

**Expected behavior**
Dependency injection selects the new provider over the old provider.

**Comment by tdonohue** [comment]
@BrandonKowalski : Could you verify how you are authenticating through Shibboleth?  Are you trying to login to the *old* "dspace-rest" API via Shibboleth?  Or are you attempting to just login to the Angular UI via Shibboleth and finding that having the "dspace-rest" webapp installed somehow blocks/affects that login?

Are you perhaps using the Shibboleth login for the old "dspace-rest" API documented here: https://wiki.lyrasis.org/pages/viewpage.action?pageId=104566810#RESTAPIv6(deprecated)-ShibbolethApacheconfigurationfortheRESTAPI

I'm a little confused how having "dspace-rest" webapp installed would change the behavior of the "server" webapp, considering they are two entirely separate webapps.  But, it *definitely* sounds like you've stumbled on something unexpected here...so, I'd appreciate it if you could walk me through your steps in a bit more detail, so that we can try and replicate them.

**Comment by BrandonKowalski** [comment]
@tdonohue I am signing in with the Angular UI using the 'Login with Shibboleth' button that appears when Shibboleth is configured.

I went to recreate this again and now am unable to reproduce what I've reported. Now logging in via the UI results in using [EPersonRestAuthenticationProvider.java](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestAuthenticationProvider.java) regardless of if the DS 6 REST API is installed. 

So now I have no idea why this provider is being used rather than the DSpaceAuthenticationProvider. Apologies for crying wolf. Looks like I have more debugging to do to figure out why the wrong provider keeps being used (and why it decided to use the correct one earlier this morning).
