### ISSUE TITLE
Unable to answer a request a copy using "helpdesk" strategy in DSpace 7.2

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#8304]
**Describe the bug**
When request a copy is enabled with helpdesk settings, if we try to either approve or reject a request for a copy by anonymous user, an error 500 occurs (see log file for details: - [dspace.log](https://github.com/DSpace/DSpace/files/8763897/dspace.log)).

Our resquest a copy are configurations are as follow: 
request.item.type = all
mail.helpdesk = (valid email of our Helpdesk)
request.item.helpdesk.override = true

The error occurs even if the user have admin permissions on the collection to which the item requested belongs.

**To Reproduce**
1. Activate request a copy with Helpdesk Strategy: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow
2. As anonymous user, look at an embargoed item, click on the file to display the request a copy form.
3. Complete and send the request a copy form
4. As helpdesk staff, look at the email inbox
5. Open the Request a copy email and click on the link to respond to it.
6. Use your DSpace Credentials to connect (_First problem, as previously this was available anonymously_)
7. On the response form try to approve or decline the request.
8. An error message appears. (_Second problem, as it's not possible to submit the request when HelpDesk strategy is enabled_)

**Expected behavior**
No error messages, the database is updated to reflect if the request has been approved or rejected and the user received the email response and, if the request has been accepted, the item file(s).

**Related work**
Don't know if this problem could relate to #8199

**Comment by amgciadev** [comment]
Hi, we have also been testing this and can confirm that we experience the same behaviour. We have also tried to approve the request logged in as a user that has the right permissions on the item and we still experience the error: Unable to perform PUT request as the current user does not have sufficient rights

This confirms that this is a separate issue to #8199

**Comment by mwoodiupui** [comment]
The problem seems to be that the `mail.helpdesk` doesn't name the logged-in user.  I'm not sure how this ever worked in the general case.  I can well imagine having a generic helpdesk mailing list that doesn't name any specific user.  I see two solutions.  

One is to invent a `Group`, put all of the authorized helpdesk `EPerson`s in it, and configure the helpdesk strategy to know which group it is.  The decision whether to permit this user to approve/deny a request would move to the strategy classes.

The other is to extend the strategy interface with a method returning `true` if the user should be checked for permission, and let the helpdesk implementation return `false`.  So, when using the helpdesk strategy, anyone who can figure out the link to a request can administer it.  I don't like this one, but it is simpler.

By the way:  if there is no user matching the helpdesk address, the strategy returns a value from the message catalog, which turns out to be "Help Desk", which is never going to match any logged-in user.

Why an `AuthorizeException` turns into a 500 is not clear to me.

**Comment by mwoodiupui** [comment]
Having looked at #8311, I see that the helpdesk strategy was *intended* to rely on security-through-obscurity, which suggests the second of my proposed fixes (or something like it).

**Comment by amgciadev** [comment]
Hi Mark, 

That is exactly how we were using it in version 5.x: with the Helpdesk strategy enabled, we specified a generic support email address (group inbox) and then anybody with access to the request approval link could approve it without having to log in. This is the only scenario that works for us because all our submitters do submit through an external system, which uses an internal administrator account in DSpace.

**Comment by tdonohue** [comment]
After discussion with @mwoodiupui , I've updated the description a bit to make it clear that this bug is specific to the Help Desk Strategy.  Not sure if we'll have time to fix this bug in 7.3, but it's flagged as high priority for 7.4.  I'll also add a note to the documentation about this bug here: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow

**Comment by tdonohue** [comment]
This has been fixed in #8319 **except for the authentication problem** which has been moved to #8636 (as it requires further analysis)
