### ISSUE TITLE
Some HAL links show a double encoding

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8333]
**Describe the bug**
Due to the current implementation of the `org.dspace.app.rest.link.HalLinkFactory.buildLink(String, T)` some HAL link can present double encoding issue. This is actually the case for the discover endpoint when the query contains characters that must be url encoded such as : 
This was noted working on https://github.com/DSpace/DSpace/pull/8238/commits/11767f5d3744224621edcc220014ce4d7d2d0bbd
Unfortunately, the proper fix proposed in the PR above introduce templated link that are actually not supported/managed on the angular side

**To Reproduce**
1. Try this API call `https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&configuration=default&query=author:sengupta&embed=thumbnail`
2. check the result, you will note that the self link is 
```
"self": {
"href": "https://api7.dspace.org/server/api/discover/search/objects?query=author%25253Asengupta&configuration=default"
}
```

**Expected behavior**
The self link should be "self": {
"href": "https://api7.dspace.org/server/api/discover/search/objects?query=author%3Asengupta&configuration=default"
}
**Related work**
Discovered/discussed in  https://github.com/DSpace/DSpace/pull/8238#discussion_r891767434

**Comment by tdonohue** [comment]
NOTE: as discussed in review of #8238... if the fix to this ticket _requires_ the introduction of templated links, then we would need to also provide an update to the UI code so that it can handle templated links.  Currently several areas of the UI will break (especially all search/browse) when templated links are encountered.  See this comment for examples: https://github.com/DSpace/DSpace/pull/8238#pullrequestreview-992169349
