### ISSUE TITLE
In DSpace 7.3, when refusing a copy request, no email is sent to the requester.

### ISSUE THREAD

**Issue by pilasou** [DSpace/DSpace#8451]
**Describe the bug**
In DSpace 7.3, if a copy request is denied, the requester does not receive any email.

**To Reproduce**
1. As anonymous user, open an embargoed item
2. Clic on an embargo file
3. Fill the online form
4. Send the request
5. In the request email sent, clic on the answer link
6. Login
7. Clic on the Deny request button
8. Send the answer.

No email is sent to the requester.

**Expected behavior**
The requester must receive an email containing the online answer form informations.

**Comment by tdonohue** [comment]
@mwoodiupui : Thoughts on this, since you helped implement this in 7.x (and continue to enhance it)?  It sounds like a possible bug...though I see from the code that it's very purposefully only sending a response when "accept" is selected: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java#L137

**Comment by nibou230** [comment]
Hi @tdonohue, as you pointed out, the "reject" response email can't be sent with the current code. We already fixed the problem on our side a couple days ago. I will create a PR in the next few minutes.
