### ISSUE TITLE
AIP exports could produce invalid mets.xml file

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8467]
**Describe the bug**
The AbstractMETSDisseminator uses the bitstream's sequenceID as fileID in the METS.
Due to the fact that the sequenceID (see linked issue) could be potentially duplicated in an item these could lead to an invalid mets

**To Reproduce**
1. force two bitstreams in the same item to have the same sequence ID
2. run the export aip script with the validate parameter or the trasmit-aip curation task of the replication task suite

**Expected behavior**
The fileID should be guarantee to be unique. The bitstream uuid can be used for this purpose

**Related work**
https://github.com/DSpace/DSpace/issues/8466

**Comment by tdonohue** [comment]
Per today's discussion in DevMtg, we decided this is a high priority bug & to move to the 7.4 board (waiting on a volunteer).  
* We'd recommend removing sequence ID from AIP exports/creation (so that new AIPs will no longer have a sequence ID)
* However, for AIP import (restore) we will need to continue to support sequence ID because previously exported AIPs may have a sequence ID... so if they are used in a restore action, that sequence ID in the AIP should also be restored (to ensure we are preserving/persisting any old bitstream URLs).
