### ISSUE TITLE
Browsing by Subject

### ISSUE THREAD

**Issue by anabe1** [DSpace/DSpace#8470]
**Describe the bug**
For "Browse by Subject", except the first page, most subject item (with small count value) shows "No items to show." when browsing.

**To Reproduce**
1. Click All of DSpace > By Subject
2. Click page 2
3. Click any subject (with small count value) on page 2
4. Search result shows "No items to show" 

**Expected behavior**
Subject items should display accordingly. 

**Related work**
https://demo7.dspace.org/browse/subject?bbm.page=2&value=Absorptive%20Capacity
![Browse By Subject (Step2)](https://user-images.githubusercontent.com/50432834/186303460-affef521-1d3a-4efe-9afe-d9a8e215797e.png)
![Browse By Subject](https://user-images.githubusercontent.com/50432834/186303464-51cc7c5d-cfb4-4644-b0d9-4130ae0cd25b.png)

**Comment by tdonohue** [comment]
@anabe1 : Thanks for reporting this.

It appears (to me) that the actual bug here is that your page doesn't reset to "page=1" when clicking on a Subject to browse by.  This makes it appear that the browse is not working.... however, if you look closely at both your URLs above, you'll see you are on `page=2` (the second page), which has no results when there is only a small list of results.

In any case, this is definitely a bug!

Another way to reproduce this issue is to simply go to page 2 (or greater) of the "browse by subject" and click on *any term on that page*.  You'll always receive "No items to show" as the page number is not auto-resetting to zero.

After that analysis, I've realized this appears to be a duplicate of https://github.com/DSpace/dspace-angular/issues/1713,  which has a PR at https://github.com/DSpace/dspace-angular/pull/1777

I've tested it today & https://github.com/DSpace/dspace-angular/pull/1777 fixes this bug.

**Comment by anabe1** [comment]
Thanks very much for the checking and fix. I 

Btw, for "Browsing by Issue Date",  the filter in the demo site, seems behave differently from the older
version, the "starts with" is more likely behaves as "equals to" now.

Understanding that the year pull-down list will become super long if listing out all years, 
that's why the design is interval by 5 or 10 years for older records (and this interval can be defined in some config file) 
In case a guest need to find 2006 data, the guest has to type the year in the input box "Filter results by date", instead of choosing it from the pull-down list (as 2006 is not an valid option in the pull-down list). 
I feel it will be more nice if there can be some remarks/ hints there, or simply change the wording "Filter results by date" (I know the label can be change in the config files), so the general guest can be "smart" enough to use input box.

**Comment by tdonohue** [comment]
NOTE: fixed by https://github.com/DSpace/dspace-angular/pull/1777 (which was just merged)
