### ISSUE TITLE
"All of DSpace" browse menu has odd behavior for Community/Collection Admins

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8512]
**Describe the bug**
Initially reported via mailing list: https://groups.google.com/g/dspace-community/c/X3bpHumqsdI/m/rT26okUkCAAJ

When you login as a Community/Collection Admin and select one of the "All of DSpace" browse options, you only see partial results.  This is reproducible on the demo site (https://demo7.dspace.org)

**To Reproduce**
1. First, while _unauthenticated_, select one of the browse-by options in "All of DSpace" menu.  Note down how many results you see (e.g. on demo site, Browse by Issue Date returns over 10,000 results.)
2. Then, log as a Community or Collection Admin.  Go to that same browse-by option.  You will see a much smaller set of results.  (e.g. on demo site, Browse by Issue Date returns only 13 results when authenticated as a Community/Collection Admin)

**Expected behavior**
Obviously, Community/Collection admins should see as many (or more) browse-by results as an anonymous user.

This issue appears to be specific to "All of DSpace" menu.  Searching and browse by Community/Collection seem to work fine.

**Comment by tdonohue** [comment]
Further testing done today.  This still exists on `main` as of today.

After further testing, I've narrowed down the issue.  It appears that, as soon as you authenticate as a Community/Collection Admin, your global browse results become **specific** to the Communities/Collections you Administer.

So, for example:
1. Setup a user who administers a single Community.  Make sure another Community exists which has at least a few Items under it.
2. Login as that user.
3. Verify that the global "Browse by Title" (`/browse/title`) is identical to the "Browse by Title" for the Community you administer (`/browse/title?scope=[community-uuid]`).  In other words, you will never see any Items *from other Communities* in the global browse.
4. Now logout so you are anonymous.  Verify that global "Browse by Title" (`/browse/title`) now includes items from all Communities.

Not sure where/how this occurs, but there's definitely some improper filtering of results here

**Comment by toniprieto** [comment]
@tdonohue I think this problem is caused by adding this filter to the solr query:

https://github.com/DSpace/DSpace/blob/8b739d4b30b78891d43e15aa8cb1b587d0360c36/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L233-L243

In previous versions, this filter was added to allow local administrators access to non-discoverable items, and has more clauses. See: 

https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L212-L237

I think we can remove this filter because it doesn't work and undiscoverable items have already been removed from browse indexes in #8642

I will submit a PR.
