### ISSUE TITLE
CC License dropdown shows duplicate values (CC0 twice)

### ISSUE THREAD

**Issue by unibravo** [DSpace/DSpace#8543]
**Describe the bug**
A clear and concise description of what the bug is.  Include the version(s) of DSpace where you've seen this problem. Link to examples if they are public.

**To Reproduce**
1. CC Lisence Activate
2. Add Item
3. Select CC Lisence 

There are 3 types showing but 2 same (CCO):

- CCO
- Creative Commons
- CCO

**Expected behavior**

- Public Domain
- CCO
- Creative Commons
- No Creative Commons Lisence

**Related work**
Link to any related tickets or PRs here.

CC Lisence Types Different at DSpace 6 and DSpace 7.x (7.3 - 7.4):

<img width="227" alt="cc-lisans-6" src="https://user-images.githubusercontent.com/22861527/197760921-3b3a5e65-961d-4241-9a93-229170525ac1.png">
<img width="215" alt="cc-lisans-7" src="https://user-images.githubusercontent.com/22861527/197760925-ca730d0f-7407-4bf2-a6af-b545b588e838.png">

**Comment by toniprieto** [comment]
It is related with #7744

I think the problem comes from the CC API. Although the query for the list of available licenses returns the CC0 i Public Domain licenses separately. See:

http://api.creativecommons.org/rest/1.5/

If you retrieve the details of the public domain license it returns the same result as CC0:

http://api.creativecommons.org/rest/1.5/license/publicdomain
http://api.creativecommons.org/rest/1.5/license/zero

I think the best option to fix this issue is to disable the Public Domain license by default including it in `cc.license.classfilter` configuration key.

**Comment by unibravo** [comment]
dspace.cfg

# A list of license classes that should be excluded from selection process
# class names - comma-separated list -  must exactly match what service returns.
# At time of implementation, these are:
# publicdomain - "Public Domain"
# standard - "Creative Commons"
# recombo - "Sampling"
# zero - "CC0"
# mark - "Public Domain Mark"
cc.license.classfilter = publicdomain, standard, recombo, zero, mark

**Comment by alexandrevryghem** [comment]
On [their wiki](https://api.creativecommons.org/docs/readme_dev.html) if you read through the 1.5 release change log you can see that this was done on purpose. So maybe it would be best to add `publicdomain` by default to `cc.license.classfilter` to avoid further confusion

> Added the `zero` license class and aliased the `publicdomain` class to issue a CC0 result.
