### ISSUE TITLE
DOIs are un-versioned even when using VersionedDOIIdentifierProvider to pre-register DOIs

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8675]
**Describe the bug**
In a repository with DOI pre-registration turned on and using the `VersionedDOIIdentifierProvider` in `identifier-service.xml`, I still get non-versioned DOIs in pre-registration when I create a new version.

**To Reproduce**
1. Use the 7.5 release (also verified in 7.6.1.. see comments below)
2. Turn on identifier pre-registration in `identifiers.cfg`
3. Use `VersionedDOIIdentifierProvider` in `identifier-service.xml`
4. Create an item
5. Create a new version of this item
6. You get an entirely new DOI, and not one using the pattern `olddoi.versionnumber`

**Expected behavior**
If you use VersionedDOIIdentifierProvider, the pre-registered DOI should use the `olddoi.versionnumber` pattern.

**Related work**
https://github.com/DSpace/DSpace/pull/8423

**Comment by pnbecker** [comment]
From a first quick analysis: this probably is a bug in VersionedDOIIdentifierProvider. To decide whether an item gets a new DOI or a history based one, it looks out for a version history of an item: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java#L67

I guess that this doesn't work for workfspaceitems. Out of my head I don't know when a new version is added to the history. I would expect that this happens when the workspace Item is created, but I would need to check this. The WorkspaceItem is a wrapper around an Item. If this item is part of the version history, we should be able to find it. To fix this bug, I would go in this direction. Unfortunately, I currently miss the time to go in there deeper.

**Comment by tdonohue** [comment]
This should be re-tested in 7.6.  It's possible that #8752 could have fixed or improved the behavior.

**Comment by olli-gold** [comment]
Unfortunately I am not able to test that with DSpace 7.6 at this time (since I am a DSpace-CRIS user), but I would be also very interested, if the bug is fixed in that version.

**Comment by MW3000** [comment]
We since moved to using the non-versioned DOIIdentifierProvider because we wish to have no semantics in our DOIs. But I will test this ASAP, as I reported the bug.

**Comment by amgciadev** [comment]
@tdonohue I have now tested this in 7.6.1 and can confirm that the issue persists. We do use versioned dois and the ability to be able to pre-register and show DOIs at submission stage would be really useful and improve our workflows considerably!

**Comment by tdonohue** [comment]
@amgciadev : Thanks for verifying this still exists in 7.6.1.  I'll leave this ticket open then in search of a volunteer.

**Comment by amgciadev** [comment]
@tdonohue I think I have found the root of the issue. I am doing some more testing and will update more details here shortly

**Comment by amgciadev** [comment]
@tdonohue just checking that this one is only waiting for reviewers now?

**Comment by tdonohue** [comment]
@amgciadev : Yes, it's waiting on reviewers.  Currently, our reviewer group is very small & many are busy doing major dependency updates right now per our Release Schedule in recent developer meetings: https://wiki.lyrasis.org/display/DSPACE/2024-03-07+DSpace+Developers+Meeting  (For instance, I am not available to do reviews at this time, but will pick them back up in mid-March)

**Comment by amgciadev** [comment]
[like]  Agustina Martinez-Garcia reacted to your message:
________________________________
