### ISSUE TITLE
OpenSearch endpoint can't generate RSS 2.0 feeds for Community/Collection without description

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#8728]
**Describe the bug**
When attempting to generate an RSS feed for a Community/Collection without `dc.description.abstract` metadata, the `/opensearch` endpoint fails with the following error
```
Invalid rss_2.0 feed, missing channel description
```

**To Reproduce**
1. Find (or create) a Community/Collection without `dc.description.abstract` metadata on https://demo7.dspace.org
2. Request `https://api7.dspace.org/server/opensearch/search?format=rss&scope=<UUID>&query=*`
   * The request will fail with HTTP 500, you'll see the above error message in the logs
  

**Expected behavior**
The feed should still work.

**Proposed solution**
Fall back to a default string (e.g. 'No description') in order to conform to the RSS 2.0 spec.

**Workaround**
Just add a `dc.description.abstract` to the Community/Collection.

**Related work**
Link to any related tickets or PRs here.

**Comment by CVamsi27** [comment]
Hello, I would like to work on this.

**Comment by tdonohue** [comment]
@CVamsi27 : Thanks! I've assigned this to you, so feel free to submit a PR when you are ready to do so.  Also, please let me know if you are doing this work on behalf of a specific institution, or if you are just donating the work yourself.  That way I can ensure I credit you or your institution in the Release Notes once the work is complete.

**Comment by CVamsi27** [comment]
I am working as an individual.

**Comment by CVamsi27** [comment]
Can I get some insights on where to begin?

**Comment by tdonohue** [comment]
@CVamsi27 : More than likely the bug is either in [OpenSearchController](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/OpenSearchController.java) or [OpenSearchServiceImpl](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/util/OpenSearchServiceImpl.java).  But, I don't know exactly where it is right now.

Once you locate the problem, you may also want to add tests to prove it is fixed into https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/opensearch/OpenSearchControllerIT.java

That's the best advice I can offer at this time... if you end up finding this more complex than expected, let us know.  We can always reassign it as needed.  Thanks!

**Comment by CVamsi27** [comment]
Can I get few UUID's with and without `dc.description.abstract`?

**Comment by ybnd** [comment]
You can use the following queries too look up some on the demo server:
- [Comm/Coll with abstract](https://demo7.dspace.org/search?query=dc.description.abstract:*%20(search.resourcetype:Collection%20OR%20search.resourcetype:Community))
- [Comm/Coll without abstract](https://demo7.dspace.org/search?query=!dc.description.abstract:*%20(search.resourcetype:Collection%20OR%20search.resourcetype:Community))

**Comment by CVamsi27** [comment]
Hello, I am trying to run a test case use the command `mvn test -DskipUnitTests=false -Dtest=[org.dspace.app.opensearch]#[emptyDescriptionTest] -DfailIfNoTests=false`. In the console it just says **Build success** nothing regarding Pass/Fail of the test case. Let we know which `cmd` to use?

**Comment by mwoodiupui** [comment]
On Fri, Apr 07, 2023 at 06:56:37AM -0700, Chandaluri Vamsi Krishna wrote:
> Hello, I am trying to run a test case use the command `mvn test -DskipUnitTests=false -Dtest=[org.dspace.app.opensearch]#[emptyDescriptionTest] -DfailIfNoTests=false`. In the console it just says **Build success** nothing regarding Pass/Fail of the test case. Let we know which `cmd` to use?

I think that should be `mvn test -DskipUnitTests=false -Dtest=org.dspace.app.opensearch#emptyDescriptionTest -DfailIfNoTests=false`

That is:  without the square brackets.  It seems that Surefire found
no matching tests and thus did nothing, successfully because of
`-DfailIfNoTests=false`.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu

**Comment by CVamsi27** [comment]
> On Fri, Apr 07, 2023 at 06:56:37AM -0700, Chandaluri Vamsi Krishna wrote: Hello, I am trying to run a test case use the command `mvn test -DskipUnitTests=false -Dtest=[org.dspace.app.opensearch]#[emptyDescriptionTest] -DfailIfNoTests=false`. In the console it just says **Build success** nothing regarding Pass/Fail of the test case. Let we know which `cmd` to use?
> I think that should be `mvn test -DskipUnitTests=false -Dtest=org.dspace.app.opensearch#emptyDescriptionTest -DfailIfNoTests=false` That is: without the square brackets. It seems that Surefire found no matching tests and thus did nothing, successfully because of `-DfailIfNoTests=false`.
> […](#)
> -- Mark H. Wood Lead Technology Analyst University Library Indiana University - Purdue University Indianapolis 755 W. Michigan Street Indianapolis, IN 46202 317-274-0749 [www.ulib.iupui.edu](http://www.ulib.iupui.edu)

I tried using that, it doesn't matter, it just says build success.

**Comment by ybnd** [comment]
@CVamsi27 I think there's two things going on
* you're missing the class name; assuming you wrote your test in the suite Tim suggested above it should be `org.dspace.app.opensearch.OpenSearchControllerIT#emptyDescriptionTest`
* this is an integration test, so you should use `-DskipIntegrationTests=false` `-Dit.test=...` instead (see [here](https://github.com/DSpace/DSpace#running-tests))
