### ISSUE TITLE
Scripts and Processes: Process Cleaner: Failed SAF import data not removed: server disk out of space risk

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8759]
**Context**

1. The UI offers a SAF import option. When you use this, it creates a process to perform the import.

https://wiki.lyrasis.org/display/DSDOC7x/Importing+and+Exporting+Items+via+Simple+Archive+Format#ImportingandExportingItemsviaSimpleArchiveFormat-UIBatchImport

2. The SAF import creates temporary data in /dspace/imports

3. The Scripts and Processes framework provides a "Process Cleaner". One of its features is to clean failed processes.

https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/administer/ProcessCleaner.java

**Describe the bug**

The process cleaner doens't remove files from failed SAF imports from the /dspace/imports file.
This is a risk for server storage going out of space, especially if imports are repeatedly tried.

**To Reproduce**
1. Perform a SAF import with an import file that doesn't meet the spec, so that it results in a failed import
2. Verify that the failed import has created new files in /dspace/imports on your server
3. Run the process cleaner with the option to remove failed processes
4. Check /dspace/imports to see if the files are still there

**Expected behavior**
Files should be cleared if we decide that the process cleaner should support this. Currently it seems that such support is simply absent/not implemented.

A different route we could take is that we are very explicit that process cleaner will NOT clean these files, and we may need to implement a separate cleaner cron.

Both approaches are likely defendable: on one hand, you could argue that the process cleaner should clean thoroughly, for all types of processes. On the other hand, the SAF import is maybe the only process that writes temporary data to /dspace/imports so you could also argue that this should be out of scope for the process cleaner.

**Related work**
Link to any related tickets or PRs here.

**Comment by mwoodiupui** [comment]
If, as I recall, the mess in `imports/` is the result of unpacking a ZIP archive, there is a third approach:  don't unpack the archive.  Read directly from the archive.  This would also eliminate a source of path-traversal vulnerabilities, as well as the need for storage for two copies (plus a bit) of the SAF package.

Regardless, we should carefully consider the questions raised above.

**Comment by tdonohue** [comment]
I have to admit, I'm sorta surprised that the SAF import process doesn't just cleanup after *itself* (or use the approach @mwoodiupui suggests).  This sounds like more of a failure of the SAF import process that it won't delete/cleanup its own temp files on a failure.  

In my opinion, the ideal is that these temp files are either not unpacked or are automatically deleted *immediately* after they are no longer needed (either import has completed or import has failed).

So, I don't think this should be a function of the Process Cleaner unless there's no other way to achieve a better design in the SAF import process itself.

**Comment by bram-atmire** [comment]
Yes, definitely also an interesting possibility or angle to make the SAF importer responsible for cleaning up after itself.

**Comment by nwoodward** [comment]
While writing a test for my fix I noticed that the importing items with a ZIP file process cleans up the `/imports` directory differently if it's run in the UI or via the command line.

In the UI, the process removes the temporary unzipped archive in `/imports/importSAF` and the `/imports/importSAF` folder itself. If the import fails then it leaves the original zip archive in `/imports`, which is I think the unremoved data referenced in this issue.

If the user is importing items via the command line then the temporary unzipped archive in `/imports/importSAF` is removed, but the empty folder itself is left there.

Because the `/imports/importSAF` _could_ be used by other import jobs running simultaneously that seems like the correct approach to me. The UI import process removes it, which is fine as long as it's the only SAF import job running at the time, but might cause problems otherwise.

I can go ahead and submit a fix that removes the original zip archive in `/imports`, but I wanted to mention this in case there's other work to be done.

**Comment by mwoodiupui** [comment]
@nwoodward Oh, dear, it's worse than that.  If there are concurrent import jobs running, and they all write to `imports/importSAF/`, what prevents them from stepping on each others' files?  If we *must* unzip to a temporary directory, each import job should create a uniquely-named directory, and clean it up properly.

It sounds like the current design assumed (correctly, in the past) that there is only one console and thus only one job will run at a time.  This is no longer true.

**Comment by nwoodward** [comment]
@mwoodiupui I noticed during testing that the import process appends the user's UUID to the zip filename (below) when working with it in the `/imports` directory. So I think for the most part that mitigates affecting other users' import jobs. That said, the UI import process shouldn't be deleting the `/imports/importSAF` folder, because like you said there could be other jobs running that use the same folder.

https://github.com/DSpace/DSpace/blob/4b1b9791ca01a069feed7fe27e8fed86323199ab/dspace-api/src/main/java/org/dspace/app/itemimport/ItemImport.java#L311-L312

**Comment by aroman-arvo** [comment]
Testing the pull request I have noticed that if you upload a non-zip file (a pdf, for example), it is not deleted from the /import directory. should it remains?

**Comment by nwoodward** [comment]
@aroman-arvo Good catch. I observe the same behavior, and it's because an error occurs before the cleanup takes place. The ItemImport and ItemImportCLI classes are missing a check for the `application/zip` MIME type of the provided file. While that needs to be fixed I think the work should take place under a new GitHub issue and PR to keep things clear and understandable.

@tdonohue thoughts? If it is going to be a new issue you can assign it to me.

**Comment by nwoodward** [comment]
One additional thought... there should be a MIME type check on the backend so that zip file imports on the command line work, but there could be a companion PR on the frontend for the Import Batch form so that the user is notified right away and the non-zip file never gets uploaded. 

<img width="1160" alt="Screen Shot 2023-05-10 at 2 28 54 PM" src="https://github.com/DSpace/DSpace/assets/1099753/603f00b9-61bd-4bd0-b4b0-241e49921e58">

**Comment by tdonohue** [comment]
@nwoodward : If there's a way to easily fix the zip validation as part of the existing PR, I'm OK with it.  

But, if you'd rather move forward the PR as-is and treat this other bug separately, then please create a separate ticket and assign yourself (I've got a lot on my plate currently, so I'll leave the decision to you).  I do agree though that it sounds like we are missing a validation of the MIME type somewhere .. and invalid MIME types likely should never be saved in the first place.  (If there's no easy way to resolve that validation though, I'm also OK with an approach of simply deleting the invalid file *after* an error occurs or server-side verification fails)

The current PR also appears to need an update as it has merge conflicts.  So, it cannot be moved forward until those are resolved.

**Comment by nwoodward** [comment]
OK, I can add MIME type validation to the PR and fix the conflicts. Due to the different ways the CLI and GUI processes manage the import file those classes will diverge further, but I think it's worth it.
