### ISSUE TITLE
GA4: GoogleAsyncEventListener causing Tomcat OOM.

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8767]
**Describe the bug**

The GoogleAsyncEventListener, used for submitting bitstream download events to Google Analytics on regular intervals, causes Java out of memory errors.

We have not yet been able to pinpoint the EXACT root cause, but are observing that a separate GoogleAsyncEventListener bean and context get created every time.

Another possible piece of this puzzle is that each individual bitstream download event is sent over a separate http connection, creating potentially a high number of connections, without timeouts or throttling, when many download events have accrued.

Instead of relying on the built-in scheduling and execution inside of Spring Boot, one strategy could be to spin this out as a separate script that we put in the hands of the linux cron scheduler, so it can run at least with its own memory allocation. But ofc, best first is to look for opportunities to reduce the memory footprint of this event delivery overall.

Code links:

https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/rest/event-service-listeners.xml#L18

https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/Application.java#L85

https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/google/GoogleAsyncEventListener.java#L96

https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/google/client/GoogleAnalyticsClientImpl.java#L54 

**To Reproduce**
1. Generate a number of bitstream downloads
2. Wait until the GoogleAsyncEventListener kicks in to send these events to Analytics
3. Observe memory usage

**Expected behavior**
Repositories with large volumes of traffic should be supported, meaning that the event delivery to Google Analytics should scale along.

**Comment by tdonohue** [comment]
Thanks for reporting @bram-atmire .  I think it'd be good to narrow down the problem (obviously) before we jump to the conclusion that the problem is the built-in scheduler.  It could be that, but it may be something else with how these events are kept in memory (and perhaps not cleared quickly, or some other sort of memory leak).

We currently use the built-in scheduler in several places, and haven't noticed memory issues with it previously.  So, while it's possible the scheduler is only having issues with the GA implementation... it's also possible there's something else in how the GA listener is storing it's data which is to blame.

Finally, I do want to stress that there's a reason we've moved tasks into this built-in scheduler...and it's to make DSpace *easier* to setup.  The more cron jobs required to setup manually, the more complexity we add to getting everything installed to run your DSpace.  That said, maybe there's a way we can allow GA listener to be configurable to use either the built-in scheduler, or an external cron, if we find the scheduler is the problem here.

All in all, this sounds like it needs more investigation into the cause.  We need to determine if it truly is the built-in scheduler to blame, or if there's something else in the GA listener code itself that is resulting in the memory leak.

Pulling over to the 7.6 board and flagging as high priority, needs volunteer

**Comment by mwoodiupui** [comment]
Granted that the problem at hand should be investigated further before rushing to a solution...

There's probably a better place for this, but..."easy" and "controllable" are antagonists.  Wearing my sysadmin. hat, I'd like at least the option to disable any hidden internal schedulers and run *periodic* tasks *only* in the main system scheduler, so it's easier to quiet the system without entirely stopping services.  I'd choose easy-to-manage over easy-to-install.  I know that's not everyone's choice.

Periodic tasks are good for work that may do much work and consume many resources.  This can include work that is created casually but need not run right away -- like the curation queues.

Aperiodic tasks are another matter.  They should start ASAP and be designed to finish quickly.  If a task is known to be rare, spin off a thread (or a subprocess) on demand -- ideally these are fire-and-forget tasks.  Otherwise an actual task scheduler is called for, and it can be internal, but it should begin work immediately when a job arrives, continuously working to keep its queue drained.  An internal task scheduler shouldn't have timed startup and one should be able to pause scheduling.  This type of scheduling is just management of scarce resources.

This ticket seems to be talking about yet another case:  a frequent task with stalls that are out of our control (i.e. networking with a busy remote service).  Cannot be guaranteed to finish quickly (for some value of "quickly").  Should probably have a work queue and thread pool of its own, and one persistent connection per thread if the remote service allows persistent connections.  Having a thousand queued tasks is better than spawning a thousand threads with network connections.  Having the ability to keep expensive resources (like a connection to a fixed target) across units of work is good too.

**Comment by bram-atmire** [comment]
Definitely agreed that _easy to setup_ VS _easy to maintain_ is an area of tension.

Whatever we do, it would benefit all repository administrators in all cases if we can make it super transparent what's happening when with server resources.

Sensible default config is great, but in some cases I'm afraid we're catering too much to the use case of a the newly established, almost empty repository with very little content and very little usage.

Which crons you decide to kick off when, and what kind of resources you allocate to them is a whole different game for huge repositories in terms of item count, assestore volume, usage, ... Not to mention the usecase where you try to run different DSpace installations on the same VM.

Just to give one example: frequently rebuilding the discovery index seems like a neat thing to keep the search index healthy. But this can take considerable time on large installations, so you want to be very deliberate and careful when you kick that off.

**Comment by bram-atmire** [comment]
Wanted to add another possible piece of the puzzle/solution. The current code has a max 20 event cap configured, for sending the events in the updates that are scheduled every 5 minutes:
https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/google/GoogleAsyncEventListener.java#L46

So what could be ALSO happening here is, if you consistently get more than 20 events every 5 minutes, the queue will keep on growing infinitely which might cause the memory blow-up, because only 20 events get processed/sent off to GA every 5 minutes.

**Comment by bram-atmire** [comment]
Not sure how I missed the following earlier, but the code already has a buffer, e.g. a defense against arbitrary high growth in the queue:

https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/google/GoogleAsyncEventListener.java#L65 

So whatever is causing the OOM, it's unlikely to be an accumulating amount of still to be sent events.

**Comment by bram-atmire** [comment]
We have not observed further occurrences anymore and are still unable to consistently reproduce this. I don't want to go as far as stating that the original OOM was _**totally**_ unrelated to the GA4 integration, but it sure looks like this. Closing out this issue for now, but if others observe it, it could always be reopened.
