### ISSUE TITLE
Shibboleth authentication could store the password in the database?

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/DSpace#8803]
Hello @tdonohue and everyone ✋

**Describe the solution you'd like**
In DSpace 6 when a user is logged in via Shibboleth the password is stored in the database, so that, users can log in via password authentication. But in DSpace 7 users cannot login via Password Authentication after creating the user via Shibboleth

**Additional context**
i need this functionality because i am not able to log in using shibboleth via api rest, because my WWW-Authenticate header location is an html, not an api rest point.

**Comment by tdonohue** [comment]
@CrisGuzmanS : This isn't possible and this didn't occur in DSpace 6.

Shibboleth is an external authentication system, which means that you are sent to Shibboleth to enter your password.  DSpace has no way to capture or save your Shibboleth password (and if it did, that'd be a security issue in Shibboleth)

Obviously, in DSpace 7, the User Interface uses the REST API for **every single activity**, and this includes authentication.  So, it is possible to login to Shibboleth via the REST API because the User Interface uses the REST API to login to Shibboleth.

I'd recommend watching the requests that the UI makes to the REST API when authenticating via Shibboleth (these can be seen in your DevTools).  Keep in mind though that authentication via Shibboleth is complex & requires HTTP redirects and even an authentication cookie.  So, a simple client like `curl` likely won't be able to login via Shib...but Angular is able to do so (as done in our UI).  The overview of the Shibboleth login process can be found in the comments of our ShibbolethLoginFilter: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/security/ShibbolethLoginFilter.java

Closing this as "won't fix".  It's not possible to save the Shibboleth password in DSpace...and we shouldn't do so even if it was possible.

**Comment by mwoodiupui** [comment]
As a user, I would be very unhappy to find that DSpace was capturing a password which Shibboleth is designed to keep secret from services like DSpace.  Fortunately this is not possible.  DSpace never sees the Shibboleth credentials, and I know of no way to get Shib to divulge a password.  The entire authentication dialog takes place in Shib, not DSpace.  One of the benefits of Shibboleth is to keep credentials *out* of relying services, to shrink the overall attack surface of a constellation of services.

OTOH as a user I might be pleased to be able to register *alternate credentials* in DSpace's own local authentication provider.  I believe that this *is* possible in v5 or v6, and I recall doing it, but I don't recall how.  Such an EPerson would have email + password hash *and* netid filled in.  The local and Shib passwords would be unrelated, and the prudent user would make certain that they are different.  This trades a bit of security for availability, so I wouldn't recommend it to most users.

**Comment by tdonohue** [comment]
@CrisGuzmanS : To be clear... it's not possible for DSpace to forward a username or password to Shibboleth.  So what you are seeing is the only possible behavior.  The DSpace REST API can *redirect* someone to Shibboleth to login..and then be notified (by Shibboleth) if that person logged in successfully.  But, there is no way to send the DSpace REST API your Shibboleth username & password to forward on to Shibboleth (if that's what you are asking).

Because Shibboleth is an external authentication system, DSpace can never see or send your Shibboleth password.  The Shibboleth password can only be entered into the Shibboleth login box.  So, what you are trying to achieve isn't possible in any system that uses Shibboleth.  External authentication systems like Shibboleth don't allow it.

**Comment by CrisGuzmanS** [comment]
Ok i understand @tdonohue and @mwoodiupui , thanks for the clarifications. So, i think i am going to use to Webscrapping to login using Shibboleth via REST API to interact with the Shibboleth user interfaz 👍 so that get the JWT
