### ISSUE TITLE
Adding/Overriding module configurations - In this case local.cfg/curate.cfg 

### ISSUE THREAD

**Issue by fribeiro-fccn** [DSpace/DSpace#8818]
I have a doubt about the module configurations and the possibility to add new curation tasks. After adding new configuration tasks to local.cfg file, all the curation tasks in the curate.cfg won't be available. To make them available again I need to include them in local.cfg.

https://github.com/DSpace/DSpace/blob/7cebc65a313066f0a79019b5c8db77bf1d8e2ac4/dspace/config/modules/curate.cfg#L19

My question:
1 - This is the expected behaviour (adding to local.cfg and adding all the other curation tasks defined in cuarte.cfg to the local.cfg)?

Example:
In my local.cfg I added 
plugin.named.org.dspace.curate.CurationTask = org.dspace.ctask.general.CurateX= curateX

But I need to add to local.cfg for example:
plugin.named.org.dspace.curate.CurationTask = org.dspace.ctask.general.ProfileFormats = profileformats

**Comment by tdonohue** [comment]
@fribeiro-fccn : This is expected behavior.  `curate.cfg` just contains "Default values".  But, as soon as you modify the value for `plugin.named.org.dspace.curate.CurationTask`, you will need to specify *all the values you want for that setting*. 

Unfortunately, there's no way to only add new values to that list in `local.cfg`... as that would mean it would be impossible to *disable* Curation Tasks that you don't want listed in `plugin.named.org.dspace.curate.CurationTask`.

Hopefully that makes sense.  If you have further questions, I'd recommend asking on one of our support options listed at: https://wiki.lyrasis.org/display/DSPACE/Support

Closing this ticket as the question was answered.
