### ISSUE TITLE
compile error ，class with underline is not found

### ISSUE THREAD

**Issue by shaw1111** [DSpace/DSpace#8823]
**Describe the bug**
like: import org.dspace.app.requestitem.RequestItem_;
only has RequestItem class, it there a tool produce that ?

thks!

**Comment by tdonohue** [comment]
@shaw1111 : These underscore (`_`) classes are required by Hibernate and are **automatically generated** by our DSpace 7 build process. 

The underscore (`_`) classes are a Hibernate feature to provide more "type safe" queries via Hibernate. See the Hibernate docs at https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/metamodelgen/MetamodelGenerator.html

For more information on why they are required, see https://www.baeldung.com/hibernate-criteria-queries-metamodel

They are automatically built/generated by our `dspace-api` here: https://github.com/DSpace/DSpace/blob/main/dspace-api/pom.xml#L54-L60

If they are not being generated for you, then you must have some other build error when you are building DSpace.  I'd recommend looking for other errors in your build process & share them via one of our support channels if you need help: https://wiki.lyrasis.org/display/DSPACE/Support

Closing this ticket as this issue is not reproducible.
