### ISSUE TITLE
Performance Issues with Groups having many EPerson members

### ISSUE THREAD

**Issue by ashishkalekar** [DSpace/DSpace#9052]
**Describe the bug**
I'm currently utilizing DSpace 7.5, where I've encountered a challenge. Within my system, there are approximately 1000 groups and 2000 members as epersons. One particular group contains 1300 members (epersons), while others have 50-100 members(epersons). When I attempt to search for the group with 1300 members (epersons) and one subgroup,  it takes a considerable amount of time to retrieve the results and when I click on edit it also takes 4-5 minutes to retrieve the current members (persons). I've also conducted tests using hal browser and found that the response time is significantly delayed.

The URL I use for this search is as follows:
`/server/api/eperson/groups/6d2c20f0-f1b1-4ce2-b613-8c6816e9b90a/epersons
`
Even when I limit the search to just one result with the **size=1** parameter:
`/server/api/eperson/groups/6d2c20f0-f1b1-4ce2-b613-8c6816e9b90a/epersons?page=0&size=1`, it still takes 3-4 minutes to receive a response. However, when I search for other groups with fewer members (50-100), the system performs smoothly.

I should mention that this issue is occurring in my local environment, using localhost:8080 and localhost:4000.

**To Reproduce**
1. Go to Access Control and click on Groups.
2. Then the Search group name in my case I have searched Students then it takes more than 4-5 minutes to retrieve the group(student).
3. After clicking on edit. again it takes 4-5 minutes to show Current Members.

**Expected behavior**
Since my other groups also require less time, it should consequently require less time.

**Comment by tdonohue** [comment]
@ashishkalekar : Thanks for creating this ticket with a clear explanation of what you are seeing.  I'll be bringing this to our next DSpace Developer's meeting (tomorrow) to make others aware and see if we can find a volunteer.  In the meantime, I've flagged this as `high priority` and pulled it over onto our 7.6.x maintenance board

**Comment by abollini** [comment]
the issue is related to this line:
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/GroupEPersonLinkRepository.java#L48

all the members in the group are retrieved directly from our Entity data model object `group.getMembers()`
we will need to use a service to retrieve just the members that belong to the requested page.
We have something similar
https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/eperson/service/EPersonService.java#L248
but it is not paginated so an overloaded method is required with the corresponding real dao implementation

**Comment by J4bbi** [comment]
This PR that made the pagesize for the number of eperson and groups on the access control page configurable, may be related https://github.com/DSpace/dspace-angular/pull/1956

**Comment by tdonohue** [comment]
Claiming this, as I've had some time today to look at the issue. I think I understand what is going on & should have a PR ready early next week.

**Comment by tdonohue** [comment]
While the primary backend issues described in this PR are "fixed" by #9078, there are also frontend issues which I've summarized in https://github.com/DSpace/dspace-angular/issues/2512  Those will require a separate fix (which I'm also working on).

**Comment by tdonohue** [comment]
I now have a more "complete" fix to this issue and https://github.com/DSpace/dspace-angular/issues/2512:

* (Additional) REST API Backend fixes: https://github.com/DSpace/DSpace/pull/9125
* Angular UI fixes: https://github.com/DSpace/dspace-angular/pull/2545

The fixes are rather large because new REST Endpoints are required to fix the behavior of the Angular UI.  They are described in https://github.com/DSpace/RestContract/pull/241
