### ISSUE TITLE
Google Sitemaps' ping endpoint is incorrectly configured and will be deprecated

### ISSUE THREAD

**Issue by J4bbi** [DSpace/DSpace#9059]
**Describe the bug**
The dspace command line tool offers the following generate sitemaps commands:

```bash
usage: org.dspace.app.sitemap.GenerateSitemaps
 -a,--ping_all      ping configured search engines
 -b,--no_htmlmap    do not generate a basic HTML sitemap
 -d,--delete        delete sitemaps dir and its contents
 -h,--help          help
 -p,--ping <arg>    ping specified search engine URL
 -s,--no_sitemaps   do not generate sitemaps.org protocol sitemap

```

Two of the options are to ping search engines to let them know of new content. The Google Sitemaps Java class currently has the repository's sitemap endpoint incorrectly configured as:

https://github.com/DSpace/DSpace/blob/375f902a06fd6b2a554c5bfda1b6fe970194523a/dspace-api/src/main/java/org/dspace/app/sitemap/GenerateSitemaps.java#L349-L350

Which would be https://sandbox.dspace.org/sitemap, using the public sandbox server as an example, however since v. 7 the sitemap path seems to have been changed to https://sandbox.dspace.org/sitemap_index.html or https://sandbox.dspace.org/sitemap_index.xml

~~I could not establish this change by any documentation. Only by looking up the `robots.txt` file in DSpace Angular: https://github.com/DSpace/dspace-angular/blob/e9b94f8e028ff8a41116c29e6c81e8ec31e1be45/src/robots.txt.ejs#L3-L4~~

In a [June 2023 statement](https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping), Google announced the ping endpoint would be deprecated by the end of the year. So that they will end in 404s. Currently, they are sending incorrect links though if used.

**Related work**
https://github.com/DSpace/DSpace/pull/9041

**Comment by tdonohue** [comment]
So, maybe the best approach here is to *remove* the `--ping` and `--ping_all` options from that `GenerateSitemaps` class?

It looks like Bing has also removed this ping option (and Google references this in their decision): https://blogs.bing.com/webmaster/may-2022/Spring-cleaning-Removed-Bing-anonymous-sitemap-submission

Since this tool is no longer used by major search engines, it seems like we should just remove it.

Needs a volunteer.  This is likely rather small/easy to remove these options completely, as that class is self contained.
