### ISSUE TITLE
Problem with the date navigation index.

### ISSUE THREAD

**Issue by victoriacruz25** [DSpace/DSpace#9062]
When I try to access the date navigation index and go to the field to select the year, it only show the year "2023", even though there are multiple items registered in different years. 

![image](https://github.com/DSpace/DSpace/assets/89466517/6ad804d2-4856-4e3e-8cbc-a290358e007b)

**Comment by alanorth** [comment]
Hi @victoriacruz25. This sounds like a Discovery indexing bug on the demo server. On my DSpace 7.6.1 test server I can browse all my issue dates.

![2023-09-12T09:10:53,146106730+03:00-fs8](https://github.com/DSpace/DSpace/assets/191754/d08a227d-4a32-4fa6-85d5-dc0ea3190e7b)

**Comment by alanorth** [comment]
@victoriacruz25 in this case the problem was on the demo.dspace.org server. It's not a bug in DSpace.

Are you having this issue on your own DSpace repository? It's better if you ask for assistance on the [DSpace mailing list](https://wiki.lyrasis.org/display/DSPACE/Mailing+Lists) or [DSpace Slack chat](https://wiki.lyrasis.org/display/DSPACE/Slack). The GitHub issue tracker is not for user support.
