### ISSUE TITLE
Install item: populateMetadata is not populating dc.date.available correctly

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#9071]
**Describe the bug**
Upon item archival the populateMetadata method is called to populate various relevant metadata fields such as dc.date.accessioned and dc.date.available.

Currently the population of dc.date.available does not take into account current embargoes on the bitstreams of the item, and still relies on the old embargo setting functionality where embargo dates where stored in the dcterms.embargo.liftdate metadata.

This is currently causing for embargoes to be ignored at archival time when setting dc.date.available and for it to always match that of dc.date.accessioned.

**Related work**
Link to any related tickets or PRs here.
I would like to work on a PR for this once the issue is confirmed and propose to use the work on this other PR #8926 to extract the embargoDate using the AccessStatus information.

**Comment by tdonohue** [comment]
@amgciadev : Thanks for creating this issue. I agree it's definitely a bug.

* `dc.date.available` does rely on the old Embargo code here: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java#L165-L168
* That code relies on the old `EmbargoService` which requires using the `embargo.field.lift` configuration to specify which metadata field stores the embargo date.
* This means, that in 7.x, a new submission almost always sets `dc.date.available` and `dc.date.accessioned` to **both be the point of deposit** (i.e. the date the item goes "in archive" after workflow approval has completed).  
    * This behavior occurs because Embargos are no longer stored in metadata fields by default. Instead, an embargo is a "startDate" to a ResourcePolicy. (If a policy has a startDate, then it will not take effect until that date passes... i.e. that object is fully inaccessible until after that data passes)

The challenge here is that I'm not sure how easy it will be to "sync" `dc.date.available` with the new Embargo information (on the ResourcePolicy), for these reasons:
1.  Embargoes can be added/removed/changed *after* an item is in the archive.  These actions are done by just modifying the ResourcePolicy (or by using the new [Bulk Access Management](https://wiki.lyrasis.org/display/DSDOC7x/Bulk+Access+Management) feature).  None of these actions result in a change/update to the `dc.date.available` metadata field.  This could mean `dc.date.available` is wrong if the embargo is changed after the submission.
2. When an Embargo date passes, there is no script that triggers or runs (as there was in the past).  Since an embargo is just a "startDate" on a ResourcePolicy, the policy just becomes "active" once the embargo date passes.  So, there's no way to easily update `dc.date.available` automatically once the embargo passes. 
3. In DSpace, it's possible to have an Item that is immediately accessible while individual Bitstreams have embargos.  In that scenario, what should happen with the `dc.date.available` field (which is on the Item object)?  Should it have no embargo, or should it somehow "find/inherit" the embargo of the Bitstream(s)?

I'm just trying to point out that the new embargo system doesn't "play well" with the old concept of the `dc.date.available` metadata field.

Overall, I understand the core use case is to find a way to share the date at which the Item becomes "un-embargoed".  However, I'm not sure that information is possible to easily track in a *metadata field*.  It is however always available from the ResourcePolicy as a "startDate".  (That "startDate" even still exists on that ResourcePolicy after the Item is available.. so it acts the same as the old `dc.date.available` metadata field)

So, I'm starting to wonder if the real need is finding a way to make the embargo date discoverable from the User Interface (and other interfaces)?  Or does that date really *need* to be _in a metadata field_?   (In other words, do we need to keep the `dc.date.available` metadata field at all? Or should we consider possibly removing it and find a better way to share the "startDate" information through the UI / REST API?)

**Comment by amgciadev** [comment]
Hi @tdonohue, thanks so much for the additional information and thinking this through. To give you a bit more context, the critical use case for us (which is applicable to the vast majority of repository) is to have easily available to our users via UI and all DSpace interfaces that allow external services to gather repository metadata (i.e. API and OAI) the date that full-text content becomes unembargoed. In the vast majority of cases relating to embargoes, they apply to content rather than the item itself but I agree with you in that we need to be able to account for all cases. 

That is why I thought using the work that I am also doing on the OAI PR (#8926) can help simplifying this a lot: by using the embargo date available in the accessStatus information we provide a default implementation of what we consider the embargo date to be, i.e. the default approach looks at either the bitstream marked as primary or the first bitstream alternatively. Repositories that wish to expose other embargo date can have their own implementation of the DefaultAccessStatusHelper plugin to incorporate their needed logic.

If we use approach in this way, you are right in that we can completely remove setting the dc.date.available which is currently not working as expected and quite misleading.

**Comment by tdonohue** [comment]
@amgciadev : Yes, we are in agreement then.  I agree that the new `DefaultAccessStatusHelper` changes you are adding in #8926 could be used as a *replacement for* the `dc.date.available`, to ensure those embargo dates are shared via the REST API and UI.  Then we could completely remove `dc.date.available` (and the rest of the old Embargo system as well).

The only thing I will note to that approach is that it will *require* sites set `showAccessStatuses: true` in the UI config.yml in order to see this info: https://github.com/DSpace/dspace-angular/blob/main/config/config.example.yml#L275   That seems reasonable to me though, as it's a minor config change... and we may want to consider setting it to "true" by default in the future if most sites need it.

**Comment by amgciadev** [comment]
@tdonohue now that #8926 is merged for 7.6.1 would the fix for this issue be as simple as removing the code for setting dc.date.available. This is how we are currently doing it in our repository. If so, happy to contribute this PR

**Comment by tdonohue** [comment]
Realized this is related directly to an old ticket #6583, so I'm linking these two together.  They both appear to be "solved" by the proposed PR #9103
