### ISSUE TITLE
DEFAULT_PAGE_SIZE does not work as expected

### ISSUE THREAD

**Issue by ddean4040** [DSpace/DSpace#9096]
**Describe the bug**
Changing the `DEFAULT_PAGE_SIZE` var in `Utils.java` does not change the default page size of results from the REST API.

**To Reproduce**
1. Change `DEFAULT_PAGE_SIZE` in `dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java` to something other than 20
2. Build DSpace and run the integration test suite - it will fail on page size and `self` link formatting due to page size change
3. Build DSpace without running tests, start it and make any paginated REST call (e.g. `/server/api/core/communities`, `/server/api/discover/browses`)
4. Check the page.size value in the response and the number of results on the page - it is 20.

**Expected behavior**
Changing the value of `DEFAULT_PAGE_SIZE` changes the default page size when using the REST API. Integration test behavior matches live system behavior.

From some testing, it looks to me like the `optionalPageable` parameter is always a Pageable object (i.e. never null) in calls to `getPageable` on a live site.

**Comment by tdonohue** [comment]
While I've not tested this to be certain, it is possible that Spring Data REST / Spring Boot (which controls the `Pageable` object) is defining the default page size in most scenarios (which may mean our `DEFAULT_PAGE_SIZE` doesn't do much of anything).

If that's the case, then I think we could override the defaults by setting this value in either the[ `application.properties`](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/resources/application.properties) file **or** in your local.cfg:
```
spring.data.rest.default-page-size=20
```
See: https://stackoverflow.com/a/34062759/3750035
(NOTE: I believe changing this value would require restarting Tomcat before the new value would take effect.)

(If for some reason that doesn't work, there is a different version of this config named `spring.data.web.pageable.default-page-size`.  However, I think DSpace uses the `spring.data.rest.*` configs since we are using Spring Data REST for our REST API.)

If someone finds time to test this, please report back with your results.  If this setting works, we could document it or add an example to `application.properties` & possibly also remove the `DEFAULT_PAGE_SIZE` variable.

**Comment by ddean4040** [comment]
Hi @tdonohue - I just tested the `spring.data.rest.default-page-size` setting in local.cfg and that works. I didn't test the application.properties file.
