### ISSUE TITLE
New user registration presents invalid token to user

### ISSUE THREAD

**Issue by fernando-lacerda** [DSpace/DSpace#9129]
**Describe the bug**
Sometimes Dspace will generate and send a 33 characters token to new user registration e-mails. When the users clicks the link, Dspace presents invalid token page. Version: 5.7.

Example case:
"Para completar seu registro no Repositório Institucional UFBA, clique no link abaixo:
 
  https://repositorio.ufba.br/register?token=eeaccfdcaf00f4276eca9d57102e2f3f
 
Se tiver alguma dúvida ou dificuldade, entre em contato com a equipe do RI por meio do e-mail: [repositorio@ufba.br](mailto:repositorio@ufba.br)
 
Equipe RI"

**To Reproduce**
Can't reproduce since it apparently happens randomly.

**Expected behavior**
Generation of a valid registration token and new user registration page presented.

**Related work**
None found.

**Comment by fernando-lacerda** [comment]
The same can happen in reset password requests

**Comment by tdonohue** [comment]
@fernando-lacerda : DSpace 5.x is no longer under support as of Jan 1, 2023. https://wiki.lyrasis.org/display/DSPACE/Releases#Releases-5.xPlatform-ENDOFLIFE   So, there will be no future releases of that platform. 

It's possible the issue was fixed in a later version of 5.x (the last was 5.11 released in July 2022).  I've not seen this issue on DSpace 7.x though, which is the currently supported version of DSpace.

Closing because 5.x is no longer under support.  If you have further questions though you are welcome to use our support lists -- there's always a chance that someone there is still running 5.x and has advice to offer. https://wiki.lyrasis.org/display/DSPACE/Support
