### ISSUE TITLE
Resource policies with null groups and eperson

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/DSpace#9190]
**Describe the bug**
The DSpace code currently does not enforce that a created resource policy has either a connected group or eperson. 
As a consequence, it can happen that a resource policy is created with neither. 

This will then cause issues down the line where DSpace assumes that all resource policies have either a group or eperson connected to it. 

**Expected behavior**
It should not be possible to have resource policy objects in the 

**Related work**
Fixed in #9191

**Comment by mwoodiupui** [comment]
I agree with your expected behavior, but for a different reason.  A policy which has neither a group nor an eperson applies to no one and should be cleanly ignored by code that makes access decisions.  Code which does not do this is broken.  Such a policy is clutter which wastes storage and time, and that is why it should not exist.  But it should not cause operational issues in correct code.
