### ISSUE TITLE
Item submission very slow when logged in EPerson is a member of many groups

### ISSUE THREAD

**Issue by aroldorique** [DSpace/DSpace#9201]
Hello everybody.

We are experiencing a slow problem when submitting new items. Some take around 2 minutes, even with small attachments. I did a test now, with just my user submitting an item without attachments and it took 15 seconds, as shown in the images below:

![3](https://github.com/DSpace/DSpace/assets/31450466/7c013002-be45-44f4-82db-974e1eb7fcf5)

![1](https://github.com/DSpace/DSpace/assets/31450466/20501a19-cfe3-4ba8-b55c-1e4c92036591)

![2](https://github.com/DSpace/DSpace/assets/31450466/81234c12-fd0a-4e7a-8f0c-5bb060e8c9d7)

I believe this slowness is related to tickets #9053 and #9164

**Comment by tdonohue** [comment]
@aroldorique : You may want to check to see if the fix for #9053 would also help with the performance of the submission form.  It might.

If it doesn't help significantly though, I expect that this ticket is essentially "the same" as #9164.  Simply put, the solution to #9164 (once we have one available) should fix any slowness in both the Submission form and Workflow page.

**Comment by tdonohue** [comment]
Closing, as this should be fixed by the solution to #9164.  The `projection=full` parameter (referenced in the screenshot in the description) has now been removed/replaced.  See #9508 (and the related PRs)
