### ISSUE TITLE
cc licenses selected through UI are assigned URIS with http:// instead of https://

### ISSUE THREAD

**Issue by emj73** [DSpace/DSpace#9323]
**Describe the bug**
cc licenses selected through UI are assigned URIS with http:// instead of https://

**To Reproduce**
1. see https://hdl.handle.net/1813/113825 as the example (in "Rights URI" field): http://creativecommons.org/licenses/by/4.0/
2. link appears to be working still and when you click on it it defaults to https but odd and needs to be corrected. 

**Expected behavior**
http://creativecommons.org/licenses/by/4.0/ should read http**s**://creativecommons.org/licenses/by/4.0/

**Related work**
sys admin shared this: this is coming directly from official source repo by dspace. Linked below. This likely hasn’t been updated because browsers automatically redirect to https in most cases and this is an informational page. there is no sensitive data like login information being transmitted. https://github.com/search?q=repo%3ADSpace%2FDSpace%20http%3A%2F%2Fcreativecommons.org%2Flicenses%2Fby%2F4.0%2F&type=codeConnect your Github account

**Comment by tdonohue** [comment]
Fixed by #9625 in the DSpace codebase.

However, please keep in mind that I believe a _complete fix_ to this issue depends on fixing #9397, as I have seen these http URLs also returned from api.creativecommons.org itself.    Nonetheless, closing this as fixed by #9625 because that PR fixes everything that we can fix _in the DSpace codebase itself_.
