### ISSUE TITLE
Upgrade arm64 build to use macos-14 runner

### ISSUE THREAD

**Issue by misilot** [DSpace/DSpace#9475]
GitHub released back in January a native arm runner for github actions, and is available for public repositories.

https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

>Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the runs-on key in your YAML workflow file to `macos-14`.

**Comment by tdonohue** [comment]
I tried this out today in #9493 and found the `macos-latest` runner (which is `macos-14`) to be **extremely slow** (slower than even emulation on ubuntu).  I'd read elsewhere that others are having a similar experience.

Unless these MacOS runners get much faster, I think we'd really need a Linux ARM64 runner, which is suggested here: https://github.com/actions/runner-images/issues/5631  (but unfortunately has no ETA).

Closing because the MacOS runners just don't seem to be worth our time.
