### ISSUE TITLE
openurltracker table should be created through "CREATE IF NOT EXISTS"

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#9514]
**Context**

The IRUS functionality to submit repository usage stats to the 3rd party IRUS collector, was previously added to DSpace through a 3rd party patch. As of DSpace 7, this functionality is part of DSpace out of the box. This feature relies on a DB table called "openurltracker"

https://wiki.lyrasis.org/display/DSDOC7x/Exchange+usage+statistics+with+IRUS

**Describe the bug**
The standard DB migration scripts will break for those institutions that previously already had the IRUS patch, and the openurltracker table in the database. 

Instead of simply trying to CREATE the openurltracker table, the DSpace 7 migration should do this as CREATE IF NOT EXISTS

**To Reproduce**
1. Load a DSpace 5 or 6 DB that already had the openurltracker table
2. Try to execute the standard DSpace 7 DB migration

**Expected behavior**
The migration should not fail because of the openurltracker table already being present.

**Comment by tdonohue** [comment]
`CREATE IF NOT EXISTS` on a table is potentially dangerous, as it just checks to see if a table **of the same name** already exists.  It does NOT verify if the tables have identical columns, etc.   See docs at https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-PARMS-IF-NOT-EXISTS

It's also worth noting that migrations are not easy to modify in FlywayDB.  Modifying an existing migration will change its checksum, and will then require **every single DSpace site** to run a `repair` in order to update to the new checksum.

For these reasons, I think we should close this as "won't fix" as this is unlikely to impact a majority of DSpace sites (because it only occurs if you have installed this table via a third-party plugin)

As a workaround, for sites that encounter this issue, they can use the `skip` command to skip the failing migration: https://wiki.lyrasis.org/display/DSDOC7x/Database+Utilities  You should obviously first verify that your table is identical to the one that DSpace 7 is trying to create.
