### ISSUE TITLE
Crossref import with DOI URI behaves incorrectly

### ISSUE THREAD

**Issue by alanorth** [DSpace/DSpace#9561]
**Describe the bug**
In DSpace 7.6.1 and current DSpace 8.0-SNAPSHOT at least, if you try to import an item using a DOI using its URI form from Crossref, you get millions of results.

<p align="center">
  <img src="https://github.com/DSpace/DSpace/assets/191754/691fedf2-451b-4808-ab7e-5f5580be18d5" width="600">
</p>

**To Reproduce**
1. Log into DSpace
2. Go to MyDSpace
3. Use the dropdown menu for importing metadata from an external source
4. Choose Crossref and enter a DOI in URI format such as https://doi.org/10.1108/CAER-03-2020-0040

**Expected behavior**
DSpace should show exactly one result for the DOI.

<p align="center">
  <img src="https://github.com/DSpace/DSpace/assets/191754/56383de1-fc3c-428c-81f9-5dd7e927404a" width="600">
</p>

Crossref's API supports retrieving the DOI in various formats, so I'm not sure what is going on. See:

- http://api.crossref.org/works/https://dx.doi.org/10.1108/CAER-03-2020-0040
- http://api.crossref.org/works/https://doi.org/10.1108/CAER-03-2020-0040
- http://api.crossref.org/works/10.1108/CAER-03-2020-0040

**Related work**
#9385

**Comment by floriangantner** [comment]
@alanorth The current implementation https://github.com/DSpace/DSpace/blob/823ade958ed42fb57f4f1de6a90a3b51fcf99304/dspace-api/src/main/java/org/dspace/importer/external/crossref/CrossRefImportMetadataSourceServiceImpl.java#L152 uses some search via query parameter, not the direct access to the doi resource.

So the effective Queries called in the search are e.g.
- https://api.crossref.org/works?query=10.1108/CAER-03-2020-0040
- https://api.crossref.org/works/?query=https://doi.org/10.1108/CAER-03-2020-0040  
containing in total the million records.

Reproduced on todays sandbox:  

![Screenshot 2024-05-13 at 13-21-28 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/0d294add-7439-4b2d-be38-8ddf045646ef)

Also searching after the title is possible.

![Screenshot 2024-05-13 at 13-19-58 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/4f9b63dc-d473-4f41-a0a0-2c9da5ab089b)

**Comment by alanorth** [comment]
@floriangantner Ah I see! It's hard to imagine this free-text search being useful. Returning more than a single page of results—leave alone millions!—is a terrible user experience. Unless there's some way to make that free-text search more useful, I would say that we should make this explicitly use DOIs because that will return an exact match and is more likely the workflow that submitters will be using (at least at our institute, where our submitters are cataloging a journal article authored by one of our scientists).

**Comment by hutattedonmyarm** [comment]
I'd blame `DoiChecker`:  https://github.com/DSpace/DSpace/blob/1517e8cd0fe59645827164099060b1d3e80b9f9f/dspace-api/src/main/java/org/dspace/importer/external/crossref/CrossRefImportMetadataSourceServiceImpl.java#L119

The crossrefimport explicitly checks if a DOI is given or not and only searches by query if no DOI is provided:

https://github.com/DSpace/DSpace/blob/1517e8cd0fe59645827164099060b1d3e80b9f9f/dspace-api/src/main/java/org/dspace/importer/external/crossref/CrossRefImportMetadataSourceServiceImpl.java#L83-L87

However only an extremely limited set of prefixes is recognized by `isDoi`:

https://github.com/DSpace/DSpace/blob/1517e8cd0fe59645827164099060b1d3e80b9f9f/dspace-api/src/main/java/org/dspace/importer/external/service/DoiCheck.java#L22

so that [https://doi.org/10.1108/CAER-03-2020-0040](http://api.crossref.org/works/https://doi.org/10.1108/CAER-03-2020-0040) is used with a query parameter and not as an ID

**Comment by alanorth** [comment]
@hutattedonmyarm Wow yes this is very simple and obviously correct. While there doesn't seem to be a single _canonical_ form for DOIs, I think it has become more common to use the `https://doi.org/10.xxxx/xxxxx` URI format in the last few years. In our repository I have begun normalizing all DOIs to that format upon deposit. [Crossref at least recommends this since 2017](https://www.crossref.org/display-guidelines/)

Could you submit a patch with your additions?
