### ISSUE TITLE
/api/eperson/epersons/search/byEmail?email=<:string> should not return 204 ("No Content")

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#9767]
## Describe the bug

Currently, the REST endpoint `/api/eperson/epersons/search/byEmail?email=<:string>` returns HTTP response code **204** / "No Content" (see https://github.com/DSpace/RestContract/blob/main/epersons.md#byemail) if no eperson with the given email address exists. This is counterintuitive and inconsistent with other REST endpoints of DSpace, e.g. `/api/core/items/<:uuid>` returns a 404 response code if no item with the given UUID can be found.

Therefore, I propose to change the response code of `/api/eperson/epersons/search/byEmail?email=<:string>` from **204** to **404** if no eperson with the given email address exists.

Changes are required in:
- Java backend (change response code 204 to 404)
- Angular frontend (evaluation of 204 response code)
- REST contract (https://github.com/DSpace/RestContract/blob/main/epersons.md#byemail)

**Comment by saschaszott** [comment]
The same inconsistent behaviour (response code 204 instead of 404) can be found in `/api/workflow/workflowitems/search/item?uuid=<:item-uuid>` and `/api/submission/workspaceitems/search/item?uuid=<:item-uuid>`.

**Comment by mwoodiupui** [comment]
This has been discussed previously, and I think these may have been some of the places that were changed from 404 to 204.  The disagreement is over whether a failure code is appropriate in the case of an **empty search result**.  One could argue that, in these requests, the path is valid because the endpoint exists, so 404 is not appropriate; it is only the query parameter that made it return nothing.  But the point is debatable.

If we change it to 404, how would one distinguish "no such object, but you made no error" from "no such endpoint, your client is broken"?

We need to make sure that we have thoroughly documented our "theory of URLs" in the API Contract, once we are agreed on what it is.

I would argue that:
- If the path leads to a working endpoint and has all required query parameters, the request is not a failure even if there is no result.
- A query that finds nothing is not a failure; it returns the empty set successfully.  204 is distinct from 202 and can be used to detect the emptiness cheaply.
- 404 is appropriate for `/api/submission/workspaceitems/search/coffeepot?uuid=1234` because there is no such endpoint.  It is not a 400 "Bad request" because it is interpretable.

**Comment by saschaszott** [comment]
I would like to add another perspective (with respect to HATEOAS): 

> However, from the perspective of a proper HATEOAS-aware client, a 204 response is problematic because there are no links to follow. When hypermedia acts as the engine of application state, when there are no links, there's no state. In other words, a 204 response throws away all application state.

(taken from https://blog.ploeh.dk/2013/04/30/rest-lesson-learned-avoid-204-responses)

**Comment by saschaszott** [comment]
@mwoodiupui , I would like to add another observation with respect to your question

> If we change it to 404, how would one distinguish "no such object, but you made no error" from "no such endpoint, your client is broken"?

Currently, `GET /api/eperson/epersons/<:uuid>` returns a 404 status code if no eperson with the given UUID exists.

**Comment by tdonohue** [comment]
@saschaszott :  I don't think we can fix this, as we've set some best practices around 404 vs 204.

404 is used when you attempt to access a resource that doesn't exist.  For instance, `GET /api/eperson/epersons/<:uuid>` if that EPerson with the given UUID doesn't exist

204 is used when the endpoint returns "empty" or no results.  It's therefore used heavily by **all `/search` endpoints** to report that your search returned zero results.

In this case. the `/api/eperson/epersons/search/byEmail?email=<:string>` should appropriately return 204 if no results are found as you are *searching* for any EPerson which may match that email string.   The intent of this endpoint is not to return whether the object exists, but rather to return any object which matches the search string.  So, hypothetically, this could even search partial email strings (though I don't think that's supported at this time).

It's not very easy for us to make *some* search endpoints respond in 204 and others respond in 404, as the intent is that all search endpoints behave similarly.

I feel this ticket should be closed as "won't fix".

**Comment by saschaszott** [comment]
@tdonohue , thanks for the explanation. Do you agree with the recommendation taken from https://blog.ploeh.dk/2013/04/30/rest-lesson-learned-avoid-204-responses to avoid **empty 204 responses** and better support HATEOAS-aware clients by extending the (empty) response with links to follow?

**Comment by tdonohue** [comment]
@saschaszott : To be honest, my understanding of a 204 is that it's supposed to have an empty body, which makes embedding links difficult... at least I'm not sure it's possible in Spring HATEOAS, which is what we use / align to on the backend.

We use 204 because it's the more appropriate response for a search that *succeeded* but returned no content: https://restfulapi.net/http-status-204-no-content/

That's much different than a 404 which means the request *failed* or the object doesn't exist.  (The search endpoint *does exist* and the search *did succeed*, but it returned zero results.)

In all honesty, return codes for REST APIs are sometimes a bit subjective.  Other applications may feel that a 404 is appropriate to return for a search, but we chose 204 as it seemed more appropriate (and can be cached by the browser).  You'll find lots of arguments on the web about 204 vs 404, and different REST APIs may use different approaches here. 

We use 204 though, and I don't see a clear reason why we should change all Searches to return a 404 when no results are found.  Returning a 404 would seem like an error (and it would require changing our User Interface to expect that for empty searches).

I'd welcome others to chime in here as well though if there are other opinions.

**Comment by mwoodiupui** [comment]
What relevant links could we present in the case of a successful search which finds nothing?

Going back up the thread a bit, I think it important that we distinguish *searches* from *fetches*.  A search which finds nothing is not a failure and should not return a 400-class status.  A fetch of a specific object which does not exist is a failure and should not return a 200-class status.

**Comment by tdonohue** [comment]
Since @mwoodiupui and I are in agreement here, I'm going to close this as "won't fix".  If additional feedback is added by others at a later time, we can always reopen if needed.  

I feel strongly that 204 (or some 2xx response) is the correct response code for a _successful_, but empty set of search results.  So, I think we'd need a clearer reason why all search endpoints should return a 404 error status for empty search results.

Sidenote: I have seen some REST APIs that return a `200 OK` for empty search results (with an empty list in the body). But, during the development of DSpace 7, we decided that 204 is what DSpace uses to represent "empty search results" (and we use it consistently for all `/search` endpoints). Changes could be made in the future, but would need careful consideration regarding any impacts to existing clients, including our User Interface.
