### ISSUE TITLE
Upgrade google error prone from 2.10.0 to latest (2.32.0)

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#9826]
## Describe the bug
The version of google error prone that we are using (7x, 8x, main) dates back from Nov 2021
If you compile DSpace with java 22, you get this error:
https://github.com/google/error-prone/issues/4370 also reported on
https://groups.google.com/g/dspace-tech/c/aDkd-k3ceGQ

This is fixed when upgrading to the latest version of error prone.

**Comment by bram-atmire** [comment]
Word of warning for anyone attempting this upgrade: some of those new checks immediately start triggering. So it's not as simple as bumping the version number, the new errors likely have to be looked at and resolved.

**Comment by mwoodiupui** [comment]
After the ERRORs are cleaned up, we should all give some attention to what our code quality tools are telling us.  There are hundreds and hundreds of warnings -- so many that we are not seeing them all, because the tools tend to stop reporting after some round number has been reached.  Some of those skipped warnings may be *important*.
